DROP INDEX IF EXISTS "IX_TaxonomyHierarchyView";
DROP VIEW IF EXISTS public."TaxonomyHierarchyView";
DROP INDEX IF EXISTS "IX_ExpositionHierarchyView";
DROP VIEW IF EXISTS public."ExpositionHierarchyView";
DROP VIEW IF EXISTS public."OrganizationHierarchyView";

DROP TABLE IF EXISTS public."JournalActionTypesToOrganizationLevels";
DROP TABLE IF EXISTS public."SpecimenImages";
DROP TABLE IF EXISTS public."UserFlaggedDistricts";
DROP TABLE IF EXISTS public."UserFlaggedSpecies";
DROP TABLE IF EXISTS public."JournalActionTypeDefinitions";
DROP TABLE IF EXISTS public."JournalEntrySpecimenAttributes";
DROP TABLE IF EXISTS public."JournalEntryAttributes";
DROP TABLE IF EXISTS public."JournalEntrySpecimens";
DROP TABLE IF EXISTS public."JournalEntryAudits";
DROP TABLE IF EXISTS public."JournalEntries";
DROP TABLE IF EXISTS public."JournalActionTypes";
DROP TABLE IF EXISTS public."SpecimenPlacements";
DROP TABLE IF EXISTS public."Markings";
DROP TABLE IF EXISTS public."SpecimenAggregatedMovements";
DROP TABLE IF EXISTS public."Zoos";
DROP TABLE IF EXISTS public."RecordSpecimens";
DROP TABLE IF EXISTS public."RecordSpecies";
DROP TABLE IF EXISTS public."Placements";
DROP TABLE IF EXISTS public."ContractActions";
DROP TABLE IF EXISTS public."Movements";
DROP TABLE IF EXISTS public."Contracts";
DROP TABLE IF EXISTS public."Cadavers";
DROP TABLE IF EXISTS public."CadaverPartners";
DROP TABLE IF EXISTS public."DocumentSpecimens";
DROP TABLE IF EXISTS public."DocumentSpecies";
DROP TABLE IF EXISTS public."Partners";
DROP TABLE IF EXISTS public."Specimens";
DROP TABLE IF EXISTS public."Species";
DROP TABLE IF EXISTS public."TaxonomyGenera";
DROP TABLE IF EXISTS public."TaxonomyFamilies";
DROP TABLE IF EXISTS public."TaxonomyOrders";
DROP TABLE IF EXISTS public."TaxonomyClasses";
DROP TABLE IF EXISTS public."TaxonomyPhyla";
DROP TABLE IF EXISTS public."ContractTypes";
DROP TABLE IF EXISTS public."ContractMovementReasons";
DROP TABLE IF EXISTS public."ContractActionTypes";
DROP TABLE IF EXISTS public."ContractActionInitiators";
DROP TABLE IF EXISTS public."SpecimenDocumentTypes";
DROP TABLE IF EXISTS public."SpeciesDocumentTypes";
DROP TABLE IF EXISTS public."RecordActionTypes";
DROP TABLE IF EXISTS public."SpeciesProtectionTypes";
DROP TABLE IF EXISTS public."ZooStatuses";
DROP TABLE IF EXISTS public."RdbCodes";
DROP TABLE IF EXISTS public."MarkingTypes";
DROP TABLE IF EXISTS public."SpeciesCiteTypes";
DROP TABLE IF EXISTS public."ClassificationTypes";
DROP TABLE IF EXISTS public."EuCodes";
DROP TABLE IF EXISTS public."GenderTypes";
DROP TABLE IF EXISTS public."OriginTypes";
DROP TABLE IF EXISTS public."IncrementReasons";
DROP TABLE IF EXISTS public."DecrementReasons";
DROP TABLE IF EXISTS public."Rearings";
DROP TABLE IF EXISTS public."BirthMethods";
DROP TABLE IF EXISTS public."Regions";
DROP TABLE IF EXISTS public."Sections";
DROP TABLE IF EXISTS public."Locations";
DROP TABLE IF EXISTS public."ExpositionSets";
DROP TABLE IF EXISTS public."ExpositionAreas";
DROP TABLE IF EXISTS public."OrganizationLevels";
DROP TABLE IF EXISTS public."UserTableSettings";
DROP TABLE IF EXISTS public."UserRoles";
DROP TABLE IF EXISTS public."Users";

CREATE TABLE public."OrganizationLevels"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "ParentId" INTEGER,
  "Level" VARCHAR(10) NOT NULL CHECK ("Level" IN ('department', 'workplace', 'district')),
  "Name" VARCHAR(255) NOT NULL,
  "Director" VARCHAR(255),
  "JournalContributorGroup" VARCHAR(1024),
  "JournalReadGroup" VARCHAR(1024),
  "JournalApproversGroup" VARCHAR(1024),
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_OrganizationLevels_OrganizationLevels  FOREIGN KEY ("ParentId") REFERENCES public."OrganizationLevels" ("Id")
);

CREATE TABLE public."ExpositionAreas"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "Name" VARCHAR(255) NOT NULL,
  "Note" VARCHAR(1000),
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public."ExpositionSets"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "ExpositionAreaId" INTEGER NOT NULL,
  "Name" VARCHAR(255) NOT NULL,
  "Note" VARCHAR(1000),
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_ExpositionSets_ExpositionAreas FOREIGN KEY ("ExpositionAreaId") REFERENCES public."ExpositionAreas" ("Id")
);

CREATE TABLE public."Locations"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "OrganizationLevelId" INTEGER,
  "ExpositionSetId" INTEGER,
  "Name" VARCHAR(255) NOT NULL,
  "ObjectNumber" INTEGER,
  "RoomNumber" INTEGER,
  "AvailableForVisitors" BOOLEAN NOT NULL DEFAULT 1,
  "LocationTypeCode" INTEGER NOT NULL,
  "AreaM2" NUMERIC(18,2),
  "CapacityM3" NUMERIC(18,2),
  "Note" VARCHAR(1000),
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Locations_OrganizationLevels FOREIGN KEY ("OrganizationLevelId") REFERENCES public."OrganizationLevels" ("Id"),
  CONSTRAINT FK_Locations_ExpositionSets FOREIGN KEY ("ExpositionSetId") REFERENCES public."ExpositionSets" ("Id")
);

-- LOOKUP TABLES

-- ADRUH
CREATE TABLE public."ContractTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- NOTE: new lookup table
CREATE TABLE public."ContractMovementReasons"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- AUKON
CREATE TABLE public."ContractActionTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- AUCASTNIK
CREATE TABLE public."ContractActionInitiators"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- DRUHDRUH
CREATE TABLE public."SpeciesDocumentTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- DRUHEXEMPLAR
CREATE TABLE public."SpecimenDocumentTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- AVYKON
CREATE TABLE public."RecordActionTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- CROCHRANA
CREATE TABLE public."SpeciesProtectionTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- NOTE: new lookup table
CREATE TABLE public."ZooStatuses"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256));

-- RDB
CREATE TABLE public."RdbCodes" -- RDB?
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256));

-- AZNACENI
CREATE TABLE public."MarkingTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- CITES
CREATE TABLE public."SpeciesCiteTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- new lookup table
CREATE TABLE public."ClassificationTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- POHLAVI
CREATE TABLE public."GenderTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- EU
CREATE TABLE public."EuCodes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- REGPUVOD
CREATE TABLE public."OriginTypes"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- PRIRUSTEK
CREATE TABLE public."IncrementReasons"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- UBYTEK 
CREATE TABLE public."DecrementReasons" -- NOTE: why order starts from 100 in the original table? 
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- ODCHOV (Rearing)
CREATE TABLE public."Rearings"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

-- NAROZENI ZPUSOB (Birth Method)
CREATE TABLE public."BirthMethods"
(
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "Sort" INTEGER NOT NULL UNIQUE,
  "DisplayName" VARCHAR(32) NOT NULL UNIQUE,
  "Note" VARCHAR(256)
);

CREATE TABLE public."Sections"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SectionName" VARCHAR(128) NOT NULL,
  "Code" VARCHAR(3)
);

-- RAJON
CREATE TABLE public."Regions"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SectionId" INTEGER NOT NULL,
  "Name" VARCHAR(128) NOT NULL,
  "Code" VARCHAR(4),
  "OperationNote" VARCHAR(32),
  CONSTRAINT FK_Regions_Sections FOREIGN KEY ("SectionId") REFERENCES public."Sections"("Id")
);

-- KMEN (Only for invertebrates)
CREATE TABLE public."TaxonomyPhyla"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "NameCz" VARCHAR(128),
  "NameLat" VARCHAR(128),
  "NameEn" VARCHAR(128),
  "NameSk" VARCHAR(128),
  "Code" VARCHAR(3),
  "ZooStatus" VARCHAR(5),
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "QuantityOwned" INTEGER NOT NULL DEFAULT 0,
  "QuantityInZoo" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedFrom" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedTo" INTEGER NOT NULL DEFAULT 0,
  "IsVertebrate" BOOLEAN NOT NULL DEFAULT(0),
  CONSTRAINT FK_TaxonomyPhyla_ZooStatuses FOREIGN KEY ("ZooStatus") REFERENCES public."ZooStatuses"("Code")
);

-- TRIDA
CREATE TABLE public."TaxonomyClasses"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "Code" VARCHAR(2),
  "NameCz" VARCHAR(128),
  "NameLat" VARCHAR(128),
  "NameEn" VARCHAR(128),
  "NameSk" VARCHAR(128),
  "Cryptogram" VARCHAR(5),
  "ImageName" VARCHAR(256),
  "Note" TEXT,
  "Synonyms" TEXT,
  "ZooStatus" VARCHAR(5),
  "Shortcut" VARCHAR(3),
  "SourceType" CHAR(1) NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "QuantityOwned" INTEGER NOT NULL DEFAULT 0,
  "QuantityInZoo" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedFrom" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedTo" INTEGER NOT NULL DEFAULT 0,
  "TaxonomyPhylumId" INTEGER NULL,
  CONSTRAINT FK_TaxonomyClasses_ZooStatuses FOREIGN KEY ("ZooStatus") REFERENCES public."ZooStatuses"("Code"),
  CONSTRAINT FK_TaxonomyClasses_TaxonomyPhyla FOREIGN KEY ("TaxonomyPhylumId") REFERENCES public."TaxonomyPhyla"("Id")
);

-- RAD
CREATE TABLE public."TaxonomyOrders"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "TaxonomyClassId" INTEGER NOT NULL,
  "Code" VARCHAR(2),
  "NameCz" VARCHAR(128),
  "NameLat" VARCHAR(128),
  "NameEn" VARCHAR(128),
  "NameSk" VARCHAR(128),
  "Note" TEXT,
  "Synonyms" TEXT,
  "ZooStatus" VARCHAR(5),
  "SourceType" CHAR(1) NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "QuantityOwned" INTEGER NOT NULL DEFAULT 0,
  "QuantityInZoo" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedFrom" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedTo" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT FK_TaxonomyOrders_TaxonomyClasses FOREIGN KEY ("TaxonomyClassId") REFERENCES public."TaxonomyClasses"("Id"),
  CONSTRAINT FK_TaxonomyOrders_ZooStatuses FOREIGN KEY ("ZooStatus") REFERENCES public."ZooStatuses"("Code")
);

-- CELED
CREATE TABLE public."TaxonomyFamilies"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "TaxonomyOrderId" INTEGER NOT NULL,
  "NameCz" VARCHAR(128),
  "NameLat" VARCHAR(128),
  "NameEn" VARCHAR(128),
  "NameSk" VARCHAR(128),
  "Code" VARCHAR(3),
  "Note" TEXT,
  "Synonyms" TEXT,
  "ZooStatus" VARCHAR(5),
  "SourceType" CHAR(1) NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "QuantityOwned" INTEGER NOT NULL DEFAULT 0,
  "QuantityInZoo" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedFrom" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedTo" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT FK_TaxonomyFamilies_TaxonomyOrders FOREIGN KEY ("TaxonomyOrderId") REFERENCES public."TaxonomyOrders"("Id"),
  CONSTRAINT FK_TaxonomyFamilies_ZooStatuses FOREIGN KEY ("ZooStatus") REFERENCES public."ZooStatuses"("Code")
);

-- ROD
CREATE TABLE public."TaxonomyGenera"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "TaxonomyFamilyId" INTEGER NOT NULL,
  "NameCz" VARCHAR(128),
  "NameLat" VARCHAR(128),
  "NameEn" VARCHAR(128),
  "NameSk" VARCHAR(128),
  "Code" VARCHAR(3),
  "ZooStatus" VARCHAR(5),
  "SourceType" CHAR(1) NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "QuantityOwned" INTEGER NOT NULL DEFAULT 0,
  "QuantityInZoo" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedFrom" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedTo" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT FK_TaxonomyGenera_TaxonomyFamilies FOREIGN KEY ("TaxonomyFamilyId") REFERENCES public."TaxonomyFamilies"("Id"),
  CONSTRAINT FK_TaxonomyGenera_ZooStatuses FOREIGN KEY ("ZooStatus") REFERENCES public."ZooStatuses"("Code")
);

-- DRUH
CREATE TABLE public."Species"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "TaxonomyGenusId" INTEGER NOT NULL,
  "Code" VARCHAR(6),
  "NameCz" VARCHAR(128),
  "NameLat" VARCHAR(128),
  "NameEn" VARCHAR(128),
  "NameGe" VARCHAR(128),
  "NameSk" VARCHAR(128),
  "Card" VARCHAR(10),
  "RdbCode" VARCHAR(5),
  "CiteType" VARCHAR(5),
  "ProtectionType" VARCHAR(5),
  "IsEep" BOOLEAN NOT NULL DEFAULT(0),
  "IsEsb" BOOLEAN NOT NULL DEFAULT(0),
  "IsIsb" BOOLEAN NOT NULL DEFAULT(0),
  "IsGenePool" BOOLEAN NOT NULL DEFAULT(0),
  "ClassificationType" VARCHAR(5) NOT NULL,
  -- NOTE: can be boolean?
  "ZooStatus" VARCHAR(5),
  "Price" NUMERIC(18,2),
  "RegionId" INTEGER,
  "Note" TEXT,
  "Synonyms" TEXT,
  "Description" TEXT,
  "FeedingRate" VARCHAR(1),
  "Photo" BYTEA,
  "UcszCoef" VARCHAR(6),
  "EuCode" VARCHAR(5),
  -- NOTE: What EU? What does that mean? regulation, protection or what?
  "IsRegulationRequirement" BOOLEAN NOT NULL DEFAULT(0),
  "GroupType" VARCHAR(1),
  "IsEuFauna" BOOLEAN NOT NULL DEFAULT(0),
  "EuFaunaRefNumber" VARCHAR(200),
  "CrExceptionRefNumber" VARCHAR(200),
  "RdbCodePrevious" VARCHAR(5),
  "AvgMinDepositInk" VARCHAR(8),
  -- NOTE: Not used, please confirm with Drozda. this is probably value related to incubation (minimal decrease)
  "AvgMaxDepositInk" VARCHAR(8),
  -- NOTE: Not used, please confirm with Drozda. this is probably value related to incubation (max decrease)
  "AvgDurationInk" VARCHAR(8),
  -- NOTE: Not used, please confirm with Drozda. this is probably value related to incubation
  "GroupId" INTEGER,
  -- NOTE: integer value probably relation FK or id from external system. Confirm with Drozada or find relation. 
  "Documentation" VARCHAR(256),
  "SourceType" CHAR(1) NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "QuantityOwned" INTEGER NOT NULL DEFAULT 0,
  "QuantityInZoo" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedFrom" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedTo" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT FK_Species_Genera FOREIGN KEY ("TaxonomyGenusId") REFERENCES public."TaxonomyGenera"("Id"),
  CONSTRAINT FK_Species_ZooStatuses FOREIGN KEY ("ZooStatus") REFERENCES public."ZooStatuses"("Code"),
  CONSTRAINT FK_Species_RdbCodes FOREIGN KEY ("RdbCode") REFERENCES public."RdbCodes"("Code"),
  CONSTRAINT FK_Species_RdbCodes_Prev FOREIGN KEY ("RdbCodePrevious") REFERENCES public."RdbCodes"("Code"),
  CONSTRAINT FK_Species_SpeciesCiteTypes FOREIGN KEY ("CiteType") REFERENCES public."SpeciesCiteTypes"("Code"),
  CONSTRAINT FK_Species_SpeciesProtectionTypes FOREIGN KEY ("ProtectionType") REFERENCES public."SpeciesProtectionTypes"("Code"),
  CONSTRAINT FK_Species_EuCodes FOREIGN KEY ("EuCode") REFERENCES public."EuCodes"("Code"),
  CONSTRAINT FK_Species_ClassificationTypes FOREIGN KEY ("ClassificationType") REFERENCES public."ClassificationTypes"("Code")
);

-- EXEMPLAR
CREATE TABLE public."Specimens"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpeciesId" INTEGER NOT NULL,
  "AccessionNumber" INTEGER,
  "GenderType" VARCHAR(5),
  "ClassificationType" VARCHAR(5) NOT NULL,
  "Zims" VARCHAR(6),
  "StudBookNumber" VARCHAR(32),
  -- Stud? PLEM is breed? -> yes it is breed = plemenna kniha
  "StudBookName" VARCHAR(32),
  "Name" VARCHAR(128),
  "Notch" VARCHAR(128),
  "Chip" VARCHAR(128),
  "RingNumber" VARCHAR(128),
  "OtherMarking" VARCHAR(128),
  "IsHybrid" BOOLEAN NOT NULL DEFAULT(0),
  "Location" VARCHAR(40),
  "IsFree" BOOLEAN NOT NULL DEFAULT(0),
  -- NOTE: does it mean something like safari?
  "BirthDate" VARCHAR(16),
  "BirthPlace" VARCHAR(32),
  "BirthMethod" VARCHAR(16),
  "Rearing" VARCHAR(10),
  "FatherId" INTEGER,
  "MotherId" INTEGER,
  "Note" TEXT,
  "OtherDetails" TEXT,
  "Photo" BYTEA,
  "RegisteredDate" VARCHAR(10),
  "RegisteredTo" VARCHAR(32),
  "RegistrationNumber" VARCHAR(128),
  "CadaverDate" VARCHAR(16),
  "CadaverPlace" VARCHAR(32),
  "EuPermit" VARCHAR(48),
  "CzechRegistrationNumber" VARCHAR(48),
  "FatherZims" VARCHAR(32),
  "MotherZims" VARCHAR(32),
  "RingNumberSecondary" VARCHAR(128),
  "OtherMarkingSecondary" VARCHAR(128),
  "ChipSecondary" VARCHAR(128),
  "NotchSecondary" VARCHAR(128),
  "Documentation" VARCHAR(256),
  -- NOTE: can be probably removed. No record it the table column.
  "Ueln" VARCHAR(48),
  -- UELN?
  "SourceType" CHAR(1) NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  -- NOTE: Calculated columns
  "InDate" VARCHAR(10),
  "InReason" VARCHAR(5),
  "InLocationId" INTEGER,
  "OutDate" VARCHAR(10),
  "OutReason" VARCHAR(5),
  "OutLocationId" INTEGER,
  "Price" NUMERIC(18,2),
  "QuantityOwned" INTEGER NOT NULL DEFAULT 0,
  "QuantityInZoo" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedFrom" INTEGER NOT NULL DEFAULT 0,
  "QuantityDeponatedTo" INTEGER NOT NULL DEFAULT 0,
  "PlacementDate" VARCHAR(10),
  "RegionId" INTEGER,
  -- NOTE: NEW PLACEMENTS
  "PlacementLocationId" INTEGER,
  "OrganizationLevelId" INTEGER,
  CONSTRAINT FK_Specimens_Species FOREIGN KEY ("SpeciesId") REFERENCES public."Species"("Id"),
  CONSTRAINT FK_Specimens_Father FOREIGN KEY ("FatherId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_Specimens_Mother FOREIGN KEY ("MotherId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_Specimens_GenderTypes FOREIGN KEY ("GenderType") REFERENCES public."GenderTypes"("Code"),
  CONSTRAINT FK_Specimens_ClassificationTypes FOREIGN KEY ("ClassificationType") REFERENCES public."ClassificationTypes"("Code"),
  CONSTRAINT FK_Specimens_Regions FOREIGN KEY ("RegionId") REFERENCES public."Regions"("Id"),
  CONSTRAINT FK_Specimens_OrganizationLevels FOREIGN KEY ("OrganizationLevelId") REFERENCES public."OrganizationLevels"("Id"),
  CONSTRAINT FK_Specimens_PlacementLocation FOREIGN KEY ("PlacementLocationId") REFERENCES public."Locations"("Id")
);

CREATE TABLE public."Partners"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "Keyword" VARCHAR(32) NOT NULL,
  "Name" VARCHAR(128),
  "Status" VARCHAR(32),
  -- Probably not correct column name. (STATUT)
  "City" VARCHAR(48),
  "StreetAddress" VARCHAR(64),
  "PostalCode" VARCHAR(10),
  "Country" VARCHAR(64),
  "Phone" VARCHAR(20),
  "Fax" VARCHAR(20),
  "Email" VARCHAR(128),
  "PartnerType" VARCHAR(4),
  -- can be removed? no data in the legacy db
  "LastName" VARCHAR(32),
  "FirstName" VARCHAR(32),
  "Note" TEXT
);

-- DOKLADD
CREATE TABLE public."DocumentSpecies"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpeciesId" INTEGER NOT NULL,
  "DocumentType" VARCHAR(5) NOT NULL,
  "Date" VARCHAR(16),
  "Number" VARCHAR(128) NOT NULL,
  "Note" TEXT,
  "IsValid" BOOLEAN NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_DocumentSpecies_Species FOREIGN KEY ("SpeciesId") REFERENCES public."Species"("Id"),
  CONSTRAINT FK_DocumentSpecies_SpeciesDocumentTypes FOREIGN KEY ("DocumentType") REFERENCES public."SpeciesDocumentTypes"("Code")
);

-- DOKLADE
CREATE TABLE public."DocumentSpecimens"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER NOT NULL,
  "DocumentType" VARCHAR(5) NOT NULL,
  "Number" VARCHAR(128) NOT NULL,
  "Date" VARCHAR(16),
  "Partner" VARCHAR(128),
  --  NOTE: it looks like it is string value from the Partners table (investigate)
  "Note" TEXT,
  "IsValid" BOOLEAN NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_DocumentSpecimens_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_DocumentSpecimens_SpecimenDocumentTypes FOREIGN KEY ("DocumentType") REFERENCES public."SpecimenDocumentTypes"("Code")
);

-- KADAVER
CREATE TABLE public."Cadavers"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER NOT NULL,
  "Date" VARCHAR(16),
  "Location" VARCHAR(128),
  -- NOTE: it is not int value as in the Movement table, but it looks like it is string value from the Partners table (investigate)
  "Note" TEXT,
  "Photo" BYTEA,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Cadavers_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id")
);

-- KADRESAR
CREATE TABLE public."CadaverPartners"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "Keyword" VARCHAR(32) NOT NULL,
  "Name" VARCHAR(128),
  "City" VARCHAR(48),
  "StreetAndNumber" VARCHAR(64),
  "PostalCode" VARCHAR(10),
  "Country" VARCHAR(64),
  "Phone" VARCHAR(20),
  "Fax" VARCHAR(20),
  "Email" VARCHAR(128),
  "LastName" VARCHAR(32),
  "FirstName" VARCHAR(32),
  "Note" TEXT,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SMLOUVA
CREATE TABLE public."Contracts"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "Number" VARCHAR(32) NOT NULL,
  "Date" VARCHAR(10) NOT NULL,
  "MovementReason" VARCHAR(5),
  "ContractType" VARCHAR(5),
  "PartnerId" INTEGER,
  "Note" TEXT,
  "NotePrague" TEXT,
  "NotePartner" TEXT,
  "Year" INTEGER,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Contracts_Partners FOREIGN KEY ("PartnerId") REFERENCES public."Partners"("Id"),
  CONSTRAINT FK_Contracts_ContractTypes FOREIGN KEY ("ContractType") REFERENCES public."ContractTypes"("Code"),
  CONSTRAINT FK_Contracts_ContractMovementReasons FOREIGN KEY ("MovementReason") REFERENCES public."ContractMovementReasons"("Code")
);

CREATE TABLE public."Movements"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER NOT NULL,
  "Date" VARCHAR(10) NOT NULL,
  "Quantity" INTEGER NOT NULL,
  "QuantityActual" INTEGER NOT NULL,
  "IncrementReason" VARCHAR(5),
  -- NOTE: Investigate if enum is same as Decrease reason and Contracts.MovementReason
  "DecrementReason" VARCHAR(5),
  "LocationId" INTEGER,
  -- NOTE: looks like it is ID of the location, probably FK from other table, relation is missing in the original table. (investigate)
  "CitesImport" VARCHAR(50),
  "CitesExport" VARCHAR(50),
  "Price" NUMERIC(18,2),
  "Note" TEXT,
  "Gender" VARCHAR(16),
  -- NOTE: not gender, What for is this? SDRPOHLAVI => original column name and values are numbers like 0,6 or 0.6.0 etc.
  "AccountingDate" VARCHAR(24),
  "PriceFinal" NUMERIC(18,2),
  -- NOTE: this is price column -> change to decimal and ask if used and purpose. confirm with drozda. 
  "DepType" CHAR(1),
  -- NOTE: this has values as null, -, + -> , probably not used, confirm with Drozda (deponace?)
  "ContractNumber" VARCHAR(32),
  -- Is the ContractNumber related to Contracts table? Is it possible to edit? There are no data in the legacy in this column. So can be probably removed.
  "ContractNote" TEXT,
  "ContractId" INTEGER,
  "SourceType" CHAR(1) NOT NULL,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Movements_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_Movements_Contracts FOREIGN KEY ("ContractId") REFERENCES public."Contracts"("Id"),
  CONSTRAINT FK_Movements_IncrementReasons FOREIGN KEY ("IncrementReason") REFERENCES public."IncrementReasons"("Code"),
  CONSTRAINT FK_Movements_DecrementReasons FOREIGN KEY ("DecrementReason") REFERENCES public."DecrementReasons"("Code")
);


-- UKONSMLOUVY
CREATE TABLE public."ContractActions"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "ContractId" INTEGER NOT NULL,
  "Date" VARCHAR(10),
  "ActionType" VARCHAR(5),
  "ActionInitiator" VARCHAR(5),
  "Note" TEXT,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_ContractActions_Contract FOREIGN KEY ("ContractId") REFERENCES public."Contracts"("Id"),
  CONSTRAINT FK_ContractActions_ContractActionTypes FOREIGN KEY ("ActionType") REFERENCES public."ContractActionTypes"("Code"),
  CONSTRAINT FK_ContractActions_ContractActionInitiators FOREIGN KEY ("ActionInitiator") REFERENCES public."ContractActionInitiators"("Code")
);

CREATE TABLE public."Placements"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER,
  "OriginSpecimenId" INTEGER,
  -- NOTE: investigate. Remove in case of A and B tables merged
  "RegionId" INTEGER NOT NULL,
  "Date" VARCHAR(10) NOT NULL,
  "Note" TEXT,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Placements_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_Placements_Regions FOREIGN KEY ("RegionId") REFERENCES public."Regions"("Id")
);

-- ZAZNAMY
CREATE TABLE public."RecordSpecimens"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER NOT NULL,
  "Date" VARCHAR(10) NOT NULL,
  "ActionType" VARCHAR(5),
  "Note" TEXT,
  "PartnerId" INTEGER,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_RecordSpecimens_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_RecordSpecimens_RecordActionTypes FOREIGN KEY ("ActionType") REFERENCES public."RecordActionTypes"("Code")
);

-- ZAZNAMY_D
CREATE TABLE public."RecordSpecies"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpeciesId" INTEGER NOT NULL,
  "Date" VARCHAR(10) NOT NULL,
  -- NOTE: we should not use Date probably as the column name
  "ActionType" VARCHAR(5),
  "Note" TEXT,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_RecordSpecies_Species FOREIGN KEY ("SpeciesId") REFERENCES public."Species"("Id"),
  CONSTRAINT FK_RecordSpecies_RecordActionTypes FOREIGN KEY ("ActionType") REFERENCES public."RecordActionTypes"("Code")
);

-- ZAHRADY
CREATE TABLE public."Zoos"
(
  "Id" VARCHAR(3) NOT NULL PRIMARY KEY,
  "Keyword" VARCHAR(32) NOT NULL,
  "Name" VARCHAR(128),
  "City" VARCHAR(48),
  "StreetNumber" VARCHAR(32),
  "PostalCode" VARCHAR(10),
  "Country" VARCHAR(64),
  "Phone" VARCHAR(20),
  "Fax" VARCHAR(20),
  "Email" VARCHAR(128),
  "Website" VARCHAR(64),
  "LastName" VARCHAR(32),
  "FirstName" VARCHAR(32),
  "Note" TEXT
);

CREATE TABLE public."Users"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "UserName" VARCHAR(256) NOT NULL,
  "VisibleTaxonomyStatuses" VARCHAR(128),
  "TaxonomySearchByCz" BOOLEAN NOT NULL DEFAULT(0),
  "TaxonomySearchByLat" BOOLEAN NOT NULL DEFAULT(1));

CREATE TABLE public."UserRoles"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "UserId" INTEGER NOT NULL,
  "RoleName" VARCHAR(256)
  CONSTRAINT FK_UserRoles_Users FOREIGN KEY ("UserId") REFERENCES public."Users"("Id"));

CREATE TABLE public."UserTableSettings"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "UserId" INTEGER NOT NULL,
  "TableId" VARCHAR(256) NOT NULL,
  "Settings" TEXT NOT NULL,
  CONSTRAINT FK_UserTableSettings_Users FOREIGN KEY ("UserId") REFERENCES public."Users"("Id"));

-- ZNACENI
CREATE TABLE public."Markings"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER NOT NULL,
  "MarkingType" VARCHAR(5) NOT NULL,
  "RingNumber" VARCHAR(32),
  "Color" VARCHAR(16),
  "Side" VARCHAR(2),
  "LocatedOn" VARCHAR(2),
  "IsValid" BOOLEAN NOT NULL DEFAULT(1),
  "MarkingDate" VARCHAR(16),
  "Note" TEXT,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Markings_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_Markings_MarkingTypes FOREIGN KEY ("MarkingType") REFERENCES public."MarkingTypes"("Code")
);

CREATE TABLE public."SpecimenPlacements"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER NOT NULL,
  "ValidSince" VARCHAR(10) NOT NULL,
  "LocationId" INTEGER,
  "OrganizationLevelId" INTEGER,
  "Note" VARCHAR(255),
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_SpecimenPlacements_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT FK_SpecimenPlacements_OrganizationLevels FOREIGN KEY ("OrganizationLevelId") REFERENCES public."OrganizationLevels"("Id"),
  CONSTRAINT FK_SpecimenPlacements_Locations FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id")
);

CREATE TABLE public."UserFlaggedDistricts"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "UserId" INTEGER NOT NULL,
  "DistrictId" INTEGER NOT NULL,
  "ModifiedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ModifiedBy" VARCHAR(64),
  CONSTRAINT FK_UserFlaggedDistricts_Users FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id"),
  CONSTRAINT FK_UserFlaggedDistricts_OrganizationLevels FOREIGN KEY ("DistrictId") REFERENCES public."OrganizationLevels" ("Id"),
  CONSTRAINT UQ_UserFlaggedDistricts_User_District UNIQUE ("UserId", "DistrictId")
);

CREATE TABLE public."UserFlaggedSpecies"
(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "UserId" INTEGER NOT NULL,
  "SpeciesId" INTEGER NOT NULL,
  "ModifiedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ModifiedBy" VARCHAR(64),
  CONSTRAINT FK_UserFlaggedSpecies_Users FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id"),
  CONSTRAINT FK_UserFlaggedSpecies_Species FOREIGN KEY ("SpeciesId") REFERENCES public."Species" ("Id"),
  CONSTRAINT UQ_UserFlaggedSpecies_User_Species UNIQUE ("UserId", "SpeciesId")
);

CREATE TABLE public."SpecimenImages" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "SpecimenId" INTEGER NOT NULL,
  "Label" VARCHAR(255) NOT NULL,
  "Description" VARCHAR(1000) NULL,
  "Image" BYTEA NOT NULL,
  "ContentType" VARCHAR(64) NOT NULL,
  "ModifiedBy" VARCHAR(64) NULL,
  "ModifiedAt" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_SpecimenImages_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id")
);

-- JOURNAL

CREATE TABLE public."JournalActionTypes" (
  "Code" VARCHAR(5) NOT NULL PRIMARY KEY,
  "JournalEntryType" VARCHAR(10) NOT NULL CHECK ("JournalEntryType" IN ('Bio', 'Movement')),
  "Sort" INTEGER NOT NULL,
  "DisplayName" VARCHAR(50) NOT NULL,
  "Note" VARCHAR(255) NULL,
  CONSTRAINT UQ_JournalEntryType_Sort UNIQUE ("JournalEntryType", "Sort"),
  CONSTRAINT UQ_JournalEntryType_DisplayName UNIQUE ("JournalEntryType", "DisplayName")
);

CREATE TABLE public."JournalEntries" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "OrganizationLevelId" INTEGER NOT NULL,
  "SpeciesId" INTEGER NOT NULL,
  "AuthorName" VARCHAR(255) NOT NULL,
  "EntryType" VARCHAR(10) CHECK ("EntryType" IN ('Bio', 'Movement')),
  "EntryDate" TIMESTAMP NOT NULL,
  "ActionTypeCode" VARCHAR(5) NOT NULL,
  "Status" VARCHAR(32) NOT NULL CHECK ("Status" IN ('1-review', '2-closed_in_review', '3-review_in_doc', '4-closed_in_doc', '5-solved_in_doc')),
  "Note" VARCHAR(1024),
  "IsLocked" BOOLEAN NOT NULL DEFAULT 0,
  "IsDeleted" BOOLEAN NOT NULL DEFAULT 0,
  "CreatedBy" VARCHAR(64) NOT NULL,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ReviewedBy" VARCHAR(64),
  "ReviewedAt" TIMESTAMP,
  "CuratorReviewNote" VARCHAR(255),
  "ArchiveReviewedBy" VARCHAR(64),
  "ArchiveReviewedAt" TIMESTAMP,
  "ArchiveReviewNote" VARCHAR(255),
  CONSTRAINT FK_JournalEntries_OrganizationLevels FOREIGN KEY ("OrganizationLevelId") REFERENCES public."OrganizationLevels"("Id"),
  CONSTRAINT FK_JournalEntries_ActionType FOREIGN KEY ("ActionTypeCode") REFERENCES public."JournalActionTypes"("Code"),
  CONSTRAINT FK_JournalEntries_Species FOREIGN KEY ("SpeciesId") REFERENCES public."Species"("Id")
);

CREATE TABLE public."JournalEntrySpecimens" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "JournalEntryId" INTEGER NOT NULL,
  "SpecimenId" INTEGER NOT NULL,
  "Note" VARCHAR(255),
  "ModifiedBy" VARCHAR(64),
  "ModifiedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_JournalEntrySpecimens_JournalEntries FOREIGN KEY ("JournalEntryId") REFERENCES public."JournalEntries"("Id"),
  CONSTRAINT FK_JournalEntrySpecimens_Specimens FOREIGN KEY ("SpecimenId") REFERENCES public."Specimens"("Id"),
  CONSTRAINT UQ_JournalEntrySpecimens UNIQUE ("JournalEntryId", "SpecimenId")
);

CREATE TABLE public."JournalEntryAttributes" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "JournalEntryId" INTEGER NOT NULL,
  "AttributeTypeCode" VARCHAR(64) NOT NULL,
  "AttributeValue" VARCHAR(1024),
  CONSTRAINT FK_JournalEntryAttributes_JournalEntries FOREIGN KEY ("JournalEntryId") REFERENCES public."JournalEntries"("Id") ON DELETE CASCADE
);

CREATE TABLE public."JournalEntrySpecimenAttributes" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "JournalEntrySpecimenId" INTEGER NOT NULL,
  "AttributeTypeCode" VARCHAR(64) NOT NULL,
  "AttributeValue" VARCHAR(1024),
  CONSTRAINT FK_JournalEntrySpecimenAttributes_JournalEntrySpecimens FOREIGN KEY ("JournalEntrySpecimenId") REFERENCES public."JournalEntrySpecimens"("Id") ON DELETE CASCADE
);

CREATE TABLE public."JournalEntryAudits" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "JournalEntryId" INTEGER NOT NULL,
  "ActionType" VARCHAR(32) NOT NULL,
  "SerializedData" TEXT NULL,
  "ModifiedBy" VARCHAR(64) NOT NULL,
  "ModifiedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_JournalEntryAudits_JournalEntries FOREIGN KEY ("JournalEntryId") REFERENCES public."JournalEntries"("Id")
);

CREATE TABLE public."JournalActionTypesToOrganizationLevels" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "ActionTypeCode" VARCHAR(5) NOT NULL,
  "OrganizationLevelId" INTEGER NOT NULL,
  CONSTRAINT FK_JournalActionTypesToOrganizationLevels_OrganizationLevels FOREIGN KEY ("OrganizationLevelId") REFERENCES public."OrganizationLevels"("Id"),
  CONSTRAINT FK_JournalActionTypesToOrganizationLevels_ActionType FOREIGN KEY ("ActionTypeCode") REFERENCES public."JournalActionTypes"("Code")
);

-- VIEWS
CREATE VIEW public."TaxonomyHierarchyView" AS
SELECT 
    sp."Id" AS SpeciesId,
    sp."NameCz" AS SpeciesNameCz,
    sp."NameLat" AS SpeciesNameLat,
    g."Id" AS GenusId,
    g."NameCz" AS GenusNameCz,
    g."NameLat" AS GenusNameLat,
    fam."Id" AS FamilyId,
    fam."NameCz" AS FamilyNameCz,
    fam."NameLat" AS FamilyNameLat,
    o."Id" AS OrderId,
    o."NameCz" AS OrderNameCz,
    o."NameLat" AS OrderNameLat,
    c."Id" AS ClassId,
    c."NameCz" AS ClassNameCz,
    c."NameLat" AS ClassNameLat,
    p."Id" AS PhylumId,
    p."NameCz" AS PhylumNameCz,
    p."NameLat" AS PhylumNameLat,
    p."IsVertebrate"
FROM public."Species" sp
INNER JOIN public."TaxonomyGenera" g ON sp."TaxonomyGenusId" = g."Id"
INNER JOIN public."TaxonomyFamilies" fam ON g."TaxonomyFamilyId" = fam."Id"
INNER JOIN public."TaxonomyOrders" o ON fam."TaxonomyOrderId" = o."Id"
INNER JOIN public."TaxonomyClasses" c ON o."TaxonomyClassId" = c."Id"
INNER JOIN public."TaxonomyPhyla" p ON c."TaxonomyPhylumId" = p."Id";

-- Create clustered index for the view
-- CREATE UNIQUE CLUSTERED INDEX "IX_TaxonomyHierarchyView" ON public."TaxonomyHierarchyView" ("SpeciesId");

CREATE VIEW public."ExpositionHierarchyView" AS
SELECT 
    loc."Id" AS LocationId,
    loc."Name" AS LocationName,
    loc."ExpositionSetId",
    es."Name" AS ExpositionSetName,
    es."ExpositionAreaId",
    ea."Name" AS ExpositionAreaName,
    loc."OrganizationLevelId" AS DistrictId
FROM public."Locations" loc
INNER JOIN public."ExpositionSets" es ON loc."ExpositionSetId" = es."Id"
INNER JOIN public."ExpositionAreas" ea ON es."ExpositionAreaId" = ea."Id";

-- CREATE UNIQUE CLUSTERED INDEX "IX_ExpositionHierarchyView" ON public."ExpositionHierarchyView" ("LocationId");

CREATE VIEW public."OrganizationHierarchyView" AS
SELECT
        itm."Id" AS "Id",
        itm."Id" AS "DistrictId",
        itm."Name" AS "DistrictName",
        p."Id" AS "WorkplaceId",
        p."Name" AS "WorkplaceName",
        pp."Id" AS "DepartmentId",
        pp."Name" AS "DepartmentName"
FROM public."OrganizationLevels" itm
JOIN public."OrganizationLevels" p ON itm."ParentId" = p."Id"
JOIN public."OrganizationLevels" pp ON p."ParentId" = pp."Id"
UNION
SELECT
        itm."Id" AS "Id",
        NULL AS "DistrictId",
        NULL AS "DistrictName",
        itm."Id" AS "WorkplaceId",
        itm."Name" AS "WorkplaceName",
        p."Id" AS "DepartmentId",
        p."Name" AS "DepartmentName"
FROM public."OrganizationLevels" itm
JOIN public."OrganizationLevels" p ON itm."ParentId" = p."Id"
WHERE itm."Level" = 'workplace'
UNION
SELECT
        itm."Id" AS "Id",
        NULL AS "DistrictId",
        NULL AS "DistrictName",
        NULL AS "WorkplaceId",
        NULL AS "WorkplaceName",
        itm."Id" AS "DepartmentId",
        itm."Name" AS "DepartmentName"
FROM public."OrganizationLevels" itm
WHERE itm."Level" = 'department';
  