export type TaxonomyClassItem = {
  id: number,
  taxonomyPhylumId?: number,
  code?: string,
  nameCz?: string,
  nameLat?: string,
  nameEn?: string,
  nameSk?: string,
  cryptogram?: string,
  note?: string,
  synonyms?: string,
  zooStatus?: string,
  quantityOwned?: number,
  quantityInZoo?: number,
  quantityDeponatedFrom?: number,
  quantityDeponatedTo?: number,
  shortcut?: string,
  modifiedBy?: string,
  modifiedAt?: string,
};