import { MRT_ColumnDef } from "material-react-table";
import { withEllipsisCell } from "~/components/ui/elipsiscell";
import { getFullDefaultVisibility } from "~/lib/utils";
import { Specimens } from "~/routes/exemplar-list/models";

export const SPECIMEN_LIST_TABLE_ID = "SPECIMEN_LIST_TABLE_ID";

export const columnDef: MRT_ColumnDef<Specimens>[] = withEllipsisCell ([
  { accessorKey: "id", header: "Id", size: 70 },
  { accessorKey: "speciesNameLat", header: "Druh (Lat.)", size: 150, enableSorting: true },
  { accessorKey: "speciesNameCz", header: "Druh (CZ)", size: 150, enableSorting: true },
  { accessorKey: "accessionNumber", header: "Př. č.", size: 70, grow: false },
  { accessorKey: "genderTypeCode", header: "Poh.", size: 70, grow: false },
  { accessorKey: "classificationTypeCode", header: "Typ", size: 70, enableSorting: false },
  { accessorKey: "zims", header: "ZIMS", size: 90 },
  { accessorKey: "studBookNumber", header: "Čís. (pl. kn.)", size: 120, enableSorting: false },
  { accessorKey: "studBookName", header: "Jméno (pl. kn.)", size: 150, enableSorting: false },
  { accessorKey: "name", header: "Domácí jméno", size: 150 },
  { accessorKey: "notch", header: "Vrub", size: 100, enableSorting: false },
  { accessorKey: "chip", header: "Chip", size: 120, enableSorting: false },
  { accessorKey: "ringNumber", header: "Kroužky", size: 120, enableSorting: false },
  { accessorKey: "otherMarking", header: "Jiné značení", size: 150, enableSorting: false },
  { accessorKey: "isHybrid", header: "Hybrid", size: 80, accessorFn: (item) => item.isHybrid ? 'ano' : '', enableSorting: false },
  { accessorKey: "location", header: "Lokace", size: 150 },
  { accessorKey: "birthDate", header: "Datum nar.", size: 100 },
  { accessorKey: "birthPlace", header: "Místo nar.", size: 150, enableSorting: false },
  { accessorKey: "birthMethod", header: "Způsob nar.", size: 120, enableSorting: false },
  { accessorKey: "rearing", header: "Odchov", size: 120, enableSorting: false },
  { accessorKey: "note", header: "Poznámka", size: 200, enableSorting: false },
  { accessorKey: "otherDetails", header: "Další detaily", size: 200, enableSorting: false },
  { accessorKey: "registeredDate", header: "Reg. kdy", size: 100, enableSorting: false },
  { accessorKey: "registeredTo", header: "Reg. komu", size: 120, enableSorting: false },
  { accessorKey: "registrationNumber", header: "Registrace", size: 120, enableSorting: false },
  { accessorKey: "cadaverDate", header: "Úhyn", size: 100, enableSorting: false },
  { accessorKey: "cadaverPlace", header: "Místo úhynu", size: 150, enableSorting: false },
  { accessorKey: "euPermit", header: "EU permit", size: 120, enableSorting: false },
  { accessorKey: "czechRegistrationNumber", header: "ČR evidence", size: 120, enableSorting: false },
  { accessorKey: "documentation", header: "Dokumentace", size: 150, enableSorting: false },
  { accessorKey: "ueln", header: "UELN", size: 120, enableSorting: false },
  { accessorKey: "modifiedBy", header: "Kdo", size: 90, enableSorting: false },
  { accessorKey: "modifiedAt", header: "Kdy", size: 90 },
  { accessorKey: "inDate", header: "Příjem", size: 100, enableSorting: false },
  { accessorKey: "inReasonCode", header: "Důvod příjmu", size: 120, enableSorting: false },
  { accessorKey: "inLocationId", header: "Odkud ID", size: 80, enableSorting: false },
  { accessorKey: "outDate", header: "Výdej", size: 100, enableSorting: false },
  { accessorKey: "outReasonCode", header: "Důvod výdeje", size: 120, enableSorting: false },
  { accessorKey: "outLocationId", header: "Kam ID", size: 80, enableSorting: false },
  { accessorKey: "price", header: "Cena", size: 80, enableSorting: false },
  { accessorKey: "quantityOwned", header: "Vlastněno", size: 90 },
  { accessorKey: "quantityInZoo", header: "V Zoo", size: 90 },
  { accessorKey: "quantityDeponatedFrom", header: "Depon. od", size: 90 },
  { accessorKey: "quantityDeponatedTo", header: "Depon. k", size: 90 },
  { accessorKey: "placementLocationId", header: "Umístění (Id)", size: 100, enableSorting: false },
  // { accessorKey: "organizationLevelId", header: "Org. úroveň ID", size: 120, enableSorting: false },
  { accessorKey: "speciesId", header: "Id druhu", size: 70 },
  { accessorKey: "speciesCode", header: "Kód druhu", size: 70, enableSorting: false },
  { accessorKey: "speciesNameEn", header: "Druh (EN)", size: 150, enableSorting: false },
  { accessorKey: "speciesIsEuFauna", header: "EU fauna", size: 70, accessorFn: (item) => item.speciesIsEuFauna ? 'ano' : '', enableSorting: false },
  { accessorKey: "speciesIsRegulationRequirement", header: "Regulační", size: 70, accessorFn: (item) => item.speciesIsRegulationRequirement ? 'ano' : '', enableSorting: false },
  { accessorKey: "genusId", header: "Id rodu", size: 70 },
  { accessorKey: "genusNameCz", header: "Rod (CZ)", size: 150, enableSorting: false },
  { accessorKey: "genusNameLat", header: "Rod (Lat.)", size: 150, enableSorting: false },
  { accessorKey: "familyId", header: "Id čeledi", size: 70 },
  { accessorKey: "familyNameCz", header: "Čeleď (CZ)", size: 150, enableSorting: false },
  { accessorKey: "familyNameLat", header: "Čeleď (Lat.)", size: 150, enableSorting: false },
  { accessorKey: "orderId", header: "Id řádu", size: 70 },
  { accessorKey: "orderCode", header: "Kód", size: 70, enableSorting: false },
  { accessorKey: "orderNameCz", header: "Řád (CZ)", size: 150, enableSorting: false },
  { accessorKey: "orderNameLat", header: "Řád (Lat.)", size: 150, enableSorting: false },
  { accessorKey: "classId", header: "Id třídy", size: 70 },
  { accessorKey: "classNameCz", header: "Třída (CZ)", size: 150, enableSorting: false },
  { accessorKey: "classNameLat", header: "Třída (Lat.)", size: 150, enableSorting: false },
  { accessorKey: "phylumId", header: "Id kmene", size: 70 },
  { accessorKey: "phylumNameCz", header: "Kmen (CZ)", size: 150, enableSorting: false },
  { accessorKey: "phylumNameLat", header: "Kmen (Lat.)", size: 150, enableSorting: false },

  // Exposition hierarchy
  { accessorKey: "locationName", header: "Umístění", size: 150, enableSorting: false },
  { accessorKey: "expositionSetId", header: "Expozice (Id)", size: 90, enableSorting: false },
  { accessorKey: "expositionSetName", header: "Expozice", size: 150, enableSorting: false },
  { accessorKey: "expositionAreaId", header: "Oblast (Id)", size: 90, enableSorting: false },
  { accessorKey: "expositionAreaName", header: "Oblast", size: 150, enableSorting: false },

  // Organization hierarchy
  { accessorKey: "districtId", header: "Rajon (Id)", size: 90, enableSorting: false },
  { accessorKey: "districtName", header: "Rajon", size: 150, enableSorting: false },
  { accessorKey: "workplaceId", header: "Pracoviště (Id)", size: 90, enableSorting: false },
  { accessorKey: "workplaceName", header: "Pracoviště", size: 150, enableSorting: false },
  { accessorKey: "departmentId", header: "Oddělení (Id)", size: 90, enableSorting: false },
  { accessorKey: "departmentName", header: "Oddělení", size: 150, enableSorting: false },
]);

export const columnDefVisibility = getFullDefaultVisibility(
  columnDef,
  [
    'id',
    'accessionNumber',
    'genderTypeCode',
    'classificationTypeCode',
    'zims',
    'studBookNumber',
    'studBookName',
    'name',
    'notch',
    'chip',
    'ringNumber',
    'speciesNameLat',
    'speciesNameCz',
    'genusNameLat',
    'genusNameCz',
    'familyNameLat',
    'familyNameCz',
    'orderNameLat',
    'orderNameCz',
    'classNameLat',
    'classNameCz',
    'phylumNameLat',
    'phylumNameCz',
    'locationName',
    'expositionSetName',
    'expositionAreaName',
    'districtName',
    'workplaceName',
    'departmentName'
  ]
);