//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pzi.Data.Import {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pzi.Data.Import.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [dbo].[JournalMovementEntryAttributes];
        ///DROP TABLE IF EXISTS [dbo].[JournalBioEntryAttributes];
        ///DROP TABLE IF EXISTS [dbo].[JournalMovementEntrySpecimens];
        ///DROP TABLE IF EXISTS [dbo].[JournalBioEntrySpecimens];
        ///DROP TABLE IF EXISTS [dbo].[JournalMovementEntries];
        ///DROP TABLE IF EXISTS [dbo].[JournalBioEntries];
        ///DROP TABLE IF EXISTS [dbo].[JournalMovementEntryTypes];
        ///DROP TABLE IF EXISTS [dbo].[JournalBioEntryTypes];
        ///DROP TABLE IF EXISTS [dbo].[SpecimenPlacements];
        ///DROP TABLE IF  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _00_RecreateDatabase_MigrationScript {
            get {
                return ResourceManager.GetString("_00_RecreateDatabase_MigrationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Lookup Tables */
        ///
        ///-- [ADRUH]
        ///INSERT INTO [dbo].[ContractTypes] ([Code], [Sort], [DisplayName])
        ///VALUES	(&apos;V&apos;, 1, N&apos;vlastní&apos;),
        ///		(&apos;C&apos;, 2, N&apos;cizí&apos;);
        ///
        ///INSERT INTO [dbo].[ContractMovementReasons] ([Code], [Sort], [DisplayName]) 
        ///VALUES	(&apos;DAR&apos;, 1, N&apos;dar&apos;),
        ///		(&apos;DEP&apos;, 2, N&apos;deponace&apos;),
        ///		(&apos;DEPD&apos;, 3, N&apos;deponace do&apos;),
        ///		(&apos;DEPZ&apos;, 4, N&apos;deponace z&apos;),
        ///		(&apos;JZ&apos;, 5, N&apos;jiný způsob&apos;),
        ///		(&apos;KUP&apos;, 6, N&apos;koupě&apos;),
        ///		(&apos;DEPR&apos;, 7, N&apos;návrat deponátu&apos;),
        ///		(&apos;DEPP&apos;, 8, N&apos;převod deponátu&apos;),
        ///		(&apos;PROD&apos;, 9, N&apos;prodej&apos;),
        ///		(&apos;V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _01_InitialTables_MigrationScript {
            get {
                return ResourceManager.GetString("_01_InitialTables_MigrationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[TaxonomyPhyla] ON;
        ///
        ///INSERT INTO [dbo].[TaxonomyPhyla] ([Id], [Code], [NameCz], [NameLat], [NameEn], [NameSk], [ZooStatus], [ModifiedBy], [ModifiedAt])
        ///VALUES (1, &apos;00&apos;, &apos;obratlovci&apos;, &apos;Vertebrates&apos;, &apos;Vertebrates&apos;, &apos;obratlovci&apos;, &apos;Z&apos;, &apos;system&apos;, GETDATE());
        ///
        ///SET IDENTITY_INSERT [dbo].[TaxonomyPhyla] OFF;
        ///
        ///-- [TRIDA] -&gt; [TaxonomyClasses] NOTE: TaxonomyPhylumId is set to 1 for all vertebrate classes
        ///
        ///PRINT(N&apos;[TRIDA] -&gt; [TaxonomyClasses]&apos;)
        ///
        ///SET IDENTITY_INSERT [dbo].[TaxonomyCl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _02_TablesA_MigrationScript {
            get {
                return ResourceManager.GetString("_02_TablesA_MigrationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @bStartId INT = 1000000;
        ///DECLARE @bSmallStartId INT = 100000;
        ///
        ///-- [KMEN_B] -&gt; [TaxonomyPhyla]
        ///
        ///PRINT(N&apos;[KMEN_B] -&gt; [TaxonomyPhyla]&apos;)
        ///
        ///SET IDENTITY_INSERT [dbo].[TaxonomyPhyla] ON;
        ///
        ///INSERT INTO [dbo].[TaxonomyPhyla] ([Id], [Code], [NameCz], [NameLat], [NameEn], [NameSk], [ZooStatus], [ModifiedBy], [ModifiedAt])
        ///SELECT @bSmallStartId + [KMEN_ID], [KOD], [NAZEV_CZ], [NAZEV_LAT], [NAZEV_EN], [NAZEV_SK], [STAVZOO], [GIOS$KDO],
        ///  CONVERT(datetime,
        ///      STUFF(STUFF(LEFT([GIOS$KDY], 8), 5, 0, &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _03_TablesB_MigrationScript {
            get {
                return ResourceManager.GetString("_03_TablesB_MigrationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static string _04_SpecimenPlacements_OrganizationLevels_Mappings {
            get {
                return ResourceManager.GetString("04_SpecimenPlacements_OrganizationLevels_Mappings", resourceCulture);
            }
        }
    }
}
