import { PrintReportType, PrintReport } from "./models";

export const printReports: PrintReport[] = [
  {
    id: 1,
    name: "Karta exempláře - ID",
    description: "Sestavy / Programy - Exempláře - Karta exempláře - ID",
    link: "specimen/specimen-card-by-id",
    type: PrintReportType.Specimen,
  },
  {
    id: 2,
    name: "Karta exemplářů - CZ",
    description: "Sestavy / Programy - Exempláře - Karty exemplářů - CZ",
    link: "specimen/specimen-card-by-cz",
    type: PrintReportType.Specimen,
  },
  {
    id: 3,
    name: "Karta exemplářů - LAT",
    description: "Sestavy / Programy - Exempláře - Karty exemplářů - LAT",
    link: "specimen/specimen-card-by-lat",
    type: PrintReportType.Specimen,
  },
  {
    id: 4,
    name: "Registrace",
    description: "Sestavy / Programy - Exempláře - Registrace",
    link: "specimen/specimen-registration",
    type: PrintReportType.Specimen,
  },
  {
    id: 5,
    name: "EU permit",
    description: "Sestavy / Programy - Exempláře - EU permit",
    link: "specimen/specimen-registered-eu-permit",
    type: PrintReportType.Specimen,
  },
  {
    id: 9,
    name: "Historie",
    description: "Sestavy/Programy-Druhy-Historie",
    link: "species/species-history",
    type: PrintReportType.Species,
  },
  {
    id: 10,
    name: "Druh v zoo",
    description: "Sestavy/Programy-Druhy-Druh v majetku",
    link: "species/in-zoo",
    type: PrintReportType.Species,
  },
  {
    id: 11,
    name: "Druh v období",
    description: "Sestavy/Programy-Druhy-Druh v období",
    link: "species/species-history-in-period",
    type: PrintReportType.Species,
  },
  {
    id: 14,
    name: "Pohyb v období s vlivem na stav v zoo",
    description: "Sestavy/Programy-Zoologie-Pohyb v období s vlivem na stav v zoo",
    link: "zoology/inventory-movements-with-influence",
    type: PrintReportType.Zoology,
  },
  {
    id: 15,
    name: "Pohyb v období bez vlivu na stav v zoo",
    description: "Sestavy/Programy-Zoologie-Pohyb v období bez vlivu na stav v zoo",
    link: "zoology/inventory-movements-no-influence",
    type: PrintReportType.Zoology,
  },
  {
    id: 16,
    name: "Pohyb v zoo podle data",
    description: "Sestavy/Programy-Zoologie-Pohyb v zoo podle data",
    link: "zoology/movement-in-zoo-by-date",
    type: PrintReportType.Zoology,
  },
  {
    id: 17,
    name: "Pohyb v zoo podle druhu",
    description: "Sestavy/Programy-Zoologie-Pohyb v zoo podle druhu",
    link: "zoology/movement-in-zoo-by-species",
    type: PrintReportType.Zoology,
  },
  {
    id: 18,
    name: "Pohyb v zoo podle rajonů",
    description: "Sestavy/Programy-Zoologie-Pohyb v zoo podle rajonu",
    link: "zoology/movement-in-zoo-by-region",
    type: PrintReportType.Zoology,
  },
  {
    id: 78,
    name: "Pohyb podle partneru",
    description: "Sestavy/Programy-Zoologie-Pohyb podle partnerů",
    link: "zoology/movement-in-zoo-by-partner",
    type: PrintReportType.Zoology,
  },
  {
    id: 20,
    name: "V majetku",
    description: "Sestavy/Programy-Zoologie-V majetku",
    link: "zoology/in-zoo-status",
    type: PrintReportType.Zoology,
  },
  {
    id: 21,
    name: "V majetku (hromadně)",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně)",
    link: "zoology/in-zoo-bulk",
    type: PrintReportType.Zoology,
  },
  {
    id: 22,
    name: "V majetku (hromadně) s reg. povinn.",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) s reg. povinností",
    link: "zoology/in-zoo-bulk-reg-only",
    type: PrintReportType.Zoology,
  },
  {
    id: 23,
    name: "V majetku (hromadně) ZCHD ČR",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) ZCHD ČR",
    link: "zoology/in-zoo-bulk-cr",
    type: PrintReportType.Zoology,
  },
  {
    id: 24,
    name: "V majetku (hromadně) s EU fauna",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) s EU fauna",
    link: "zoology/in-zoo-bulk-eu-fauna",
    type: PrintReportType.Zoology,
  },
  {
    id: 25,
    name: "V majetku (hromadně) bez EUpermit s reg. povinn.",
    description:
      "Sestavy/Programy-Zoologie-V majetku (hromadně) bez Eupermit s reg. povinností",
    link: "zoology/in-zoo-bulk-no-eu-reg-only",
    type: PrintReportType.Zoology,
  },
  {
    id: 26,
    name: "V majetku (hromadně) bez EUpermit",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) bez Eupermit",
    link: "zoology/in-zoo-bulk-no-eu",
    type: PrintReportType.Zoology,
  },
  {
    id: 27,
    name: "V majetku (hromadně) ne 've stavu'",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) ne 've stavu'",
    link: "zoology/in-zoo-bulk-not-in-state",
    type: PrintReportType.Zoology,
  },
  {
    id: 28,
    name: "V majetku (hromadně) podle rozhodnutí",
    description:
      "Sestavy/Programy-Zoologie-V majetku (hromadně) podle rozhodnutí",
    link: "zoology/in-zoo-bulk-by-decision",
    type: PrintReportType.Zoology,
  },
  {
    id: 29,
    type: PrintReportType.Zoology,
    name: 'V majetku po rajonech',
    description: 'Sestavy/Programy-Zoologie-V majetku po rajonech',
    link: 'zoology/in-zoo-by-region'
  },
  {
    id: 30,
    name: "V majetku rajonu",
    description: "Sestavy/Programy-Zoologie-V majetku rajonu",
    link: "zoology/species-in-region",
    type: PrintReportType.Zoology,
  },
  {
    id: 31,
    name: "V majetku úseku",
    description: "Sestavy/Programy-Zoologie-V majetku úseku",
    link: "zoology/species-in-department",
    type: PrintReportType.Zoology,
  },
  {
    id: 32,
    name: "Seznam exemplářů pro ZIMS v období",
    description: "Sestavy/Programy-Zoologie-Seznam exemplářů pro ARKS v období",
    link: "zoology/specimens-for-zims-at-date-range",
    type: PrintReportType.Zoology,
  },
  {
    id: 33,
    name: "Kompletní seznam - ZIMS",
    description: "Sestavy/Programy-Zoologie-Kompletní seznam - ARKS",
    link: "zoology/full-list-by-zims",
    type: PrintReportType.Zoology,
  },
  {
    id: 34,
    name: "Seznam registrací - podle čísla registrace",
    description:
      "Sestavy/Programy-Zoologie- Seznam registrací - podle čísla registrace",
    link: "zoology/registrations-list-by-number",
    type: PrintReportType.Zoology,
  },
  {
    id: 35,
    name: "Seznam registrací - podle data úbytku",
    description:
      "Sestavy/Programy-Zoologie- Seznam registrací - podle data úbytku",
    link: "zoology/registrations-list-by-date",
    type: PrintReportType.Zoology,
  },
  {
    id: 36,
    name: "Seznam EU-permit - podle čísla ",
    description: "Sestavy/Programy-Zoologie- Seznam EU-permit - podle čísla",
    link: "zoology/registrations-list-by-eu-permit",
    type: PrintReportType.Zoology,
  },
  {
    id: 38,
    name: "ČR rozhodnutí - podle data pohybu",
    description: "Sestavy/Programy-Zoologie- ČR rozhodnutí - podle data pohybu",
    link: "zoology/cr-decision-by-movement-date",
    type: PrintReportType.Zoology,
  },
  {
    id: 37,
    name: "ČR evidence - podle data pohybu",
    description: "Sestavy/Programy-Zoologie- ČR evidence - podle data pohybu",
    link: "zoology/cr-evidence-by-movement-date",
    type: PrintReportType.Zoology,
  },
  {
    id: 39,
    name: "Narození v období",
    description: "Sestavy/Programy-Zoologie- Narození v období",
    link: "zoology/births-in-period",
    type: PrintReportType.Zoology,
  },
  {
    id: 40,
    name: "Statistika narození",
    description: "Sestavy/Programy-Zoologie- Statistika narození",
    link: "zoology/statistic-births",
    type: PrintReportType.Zoology,
  },
  {
    id: 41,
    name: "Statistika ke dni",
    description: "Sestavy/Programy-Zoologie- Statistika ke dni",
    link: "zoology/statistics-as-of-date",
    type: PrintReportType.Zoology,
  },
  {
    id: 42,
    name: "Statistika ke dni s mez. programy",
    description:
      "Sestavy/Programy-Zoologie- Statistika ke dni s mez. programy",
    link: "zoology/zoology-statistics-eep",
    type: PrintReportType.Zoology,
  },
  {
    id: 43,
    name: "Statistika ke dni s mez. programy dle MŽP ČR",
    description:
      "Sestavy/Programy-Zoologie- Statistika ke dni s mez. programy dle MZP ČR",
    link: "zoology/zoology-statistics-eep-mzp",
    type: PrintReportType.Zoology,
  },
  {
    id: 44,
    name: "Statistika ke dni podle řádu",
    description: "Sestavy/Zoologie-Statistika ke dni podle řádu",
    link: "zoology/statistics-by-order",
    type: PrintReportType.Zoology,
  },
  {
    id: 45,
    name: "Přehled druhů 'eu-odchylka'",
    description: "Sestavy/Programy-Zoologie- Přehled druhu EU odchylka",
    link: "zoology/eu-divergence",
    type: PrintReportType.Zoology,
  },
  {
    id: 46,
    name: "Zvláště chráněné druhy ČR",
    description: "Sestavy/Zoologie-Zvláště chráněné druhy ČR",
    link: "zoology/cr-protected",
    type: PrintReportType.Zoology,
  },
  {
    id: 47,
    name: "EU fauna",
    description: "Sestavy/Zoologie-EU fauna",
    link: "zoology/eu-fauna",
    type: PrintReportType.Zoology,
  },
  {
    id: 48,
    name: "Kadáver v období",
    description: "Sestavy/Programy-Zoologie- Kadáver v období",
    link: "zoology/statistics-cadavers-table",
    type: PrintReportType.Zoology,
  },
  {
    id: 49,
    name: "Kadáver v období pro druh",
    description: "Sestavy/Programy-Zoologie- Kadáver v období pro druh",
    link: "zoology/statistics-cadavers-by-species",
    type: PrintReportType.Zoology,
  },
  {
    id: 50,
    name: "Kadáver v období pro místo",
    description:
      "Sestavy/Programy-Zoologie- Kadáver v období pro místo",
    link: "zoology/statistics-cadavers-by-location",
    type: PrintReportType.Zoology,
  },
  {
    id: 51,
    name: "Přehled záznamů kadáver v období",
    description: "Sestavy/Programy-Zoologie- Přehled záznamů kadáverů v období",
    link: "zoology/statistics-cadavers-overview",
    type: PrintReportType.Zoology,
  },
  {
    id: 52,
    name: "Inventura",
    description: "Sestavy/Programy-Ekonomika-Inventura",
    link: "zoology/species-inventory",
    type: PrintReportType.Economy,
  },
  {
    id: 54,
    name: "Inventura po rajonech",
    description: "Sestavy/Programy-Ekonomika-Inventura po rajonech",
    link: "economy/region-inventory-all",
    type: PrintReportType.Economy,
  },
  {
    id: 55,
    name: "Inventura rajonů",
    description: "Sestavy/Programy-Ekonomika-Inventura rajonu",
    link: "economy/region-inventory",
    type: PrintReportType.Economy,
  },
  {
    id: 56,
    name: "Inventura úseku",
    description: "Sestavy/Programy-Ekonomika-Inventura úseku",
    link: "economy/section-inventory",
    type: PrintReportType.Economy,
  },
  {
    id: 57,
    name: "Přehled ekonomiky pohybu",
    description: "Sestavy/Programy - Ekonomika - Prehled ekonomiky pohybu",
    link: "economy/economy-of-movement-overview",
    type: PrintReportType.Economy,
  },
  {
    id: 58,
    name: "Rekapitulace ekonomiky pohybu",
    description: "Sestavy/Programy - Ekonomika - Rekapitulace ekonomiky pohybu",
    link: "economy/economy-of-movement-recap",
    type: PrintReportType.Economy,
  },
  {
    id: 60,
    name: "Ekonomika pohybu - podle tříd",
    description: "Sestavy/Programy - Ekonomika - Ekonomika pohybu - podle trid",
    link: "economy/economy-of-movement-summary",
    type: PrintReportType.Economy,
  },
  {
    id: 61,
    name: "Přehled pohybu - koupě/prodej",
    description: "Sestavy/Programy - Ekonomika - Přehled pohybu - koupě/prodej",
    link: "economy/economy-of-movement-transactions",
    type: PrintReportType.Economy,
  },
  {
    id: 62,
    name: " Přehled smlouv podle masky čísla smlouvy",
    description: "Sestavy/Programy - Ekonomika - Přehled smluv podle masky čísla",
    link: "economy/contracts-by-number-mask",
    type: PrintReportType.Economy,
  },
  {
    id: 63,
    name: "Přehled smlouv za období",
    description: "Sestavy/Programy - Ekonomika - Přehled smluv za období",
    link: "economy/contracts-by-date",
    type: PrintReportType.Economy,
  },
  {
    id: 64,
    name: "Deponace",
    description: "Sestavy/Programy-Ekonomika-Deponace",
    link: "economy/inventory-deponated",
    type: PrintReportType.Economy,
  },
  {
    id: 67,
    name: "Zabavené druhy ke dni",
    description: "Sestavy/Programy-Ekonomika-Zabavené druhy ke dni",
    link: "economy/seized-species",
    type: PrintReportType.Economy,
  },
  {
    id: 69,
    name: "Zabavené exempláře ke dni",
    description: "Sestavy/Programy-Ekonomika-Zabavené exempláře ke dni",
    link: "economy/seized-specimens",
    type: PrintReportType.Economy,
  },
  {
    id: 71,
    name: "Zabavené exempláře - všechny",
    description: "Sestavy/Programy-Ekonomika-Zabavené exempláře - všechny",
    link: "economy/seized-specimens-all",
    type: PrintReportType.Economy,
  },
  {
    id: 73,
    name: "Zabavené exempláře - krmné dny",
    description: "Sestavy/Programy - Ekonomika - Zabavené exempláře - krmné dny",
    link: "economy/feeding-days-seized",
    type: PrintReportType.Economy,
  },
  {
    id: 74,
    name: "Krmné dny druhu",
    description: "Sestavy/Programy - Ekonomika - Krmné dny druhu",
    link: "economy/feeding-days",
    type: PrintReportType.Economy,
  },
  {
    id: 75,
    name: "Krmné dny pro dotaci",
    description: "Sestavy/Programy - Ekonomika - Krmné dny pro dotaci",
    link: "economy/feeding-days-for-donation",
    type: PrintReportType.Economy,
  },
  {
    id: 79,
    name: "Dotaz k deponacím - CZ",
    description: "Sestavy/Korespondence - Dotaz k deponacím - česká verze",
    link: "economy/deposit-inquiry-cz",
    type: PrintReportType.Correspondence,
  },
  {
    id: 80,
    name: "Dotaz k deponacím - ENG",
    description: "Sestavy/Korespondence - Dotaz k deponacím - anglická verze",
    link: "economy/deposit-inquiry-eng",
    type: PrintReportType.Correspondence,
  },
  {
    id: 81,
    name: "Obálka",
    description: "Obálka pro partnery a zahrady",
    type: PrintReportType.Economy,
    link: "economy/envelope"
  }
];
