import { PrintReportType, PrintReport } from "./models";

export const printReportsFull: PrintReport[] = [
  {
    id: 1,
    name: "Karta exempláře - ID",
    description: "Sestavy / Programy - Exempláře - Karta exempláře - ID",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 2,
    name: "Karta exemplářů - CZ",
    description: "Sestavy / Programy - Exempláře - Karty exemplářů - CZ",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 3,
    name: "Karta exemplářů - LAT",
    description: "Sestavy / Programy - Exempláře - Karty exemplářů - LAT",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 4,
    name: "Registrace",
    description: "Sestavy / Programy - Exempláře - Registrace",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 5,
    name: "EU permit",
    description: "Sestavy / Programy - Exempláře - EU permit",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 6,
    name: "ČR evidence",
    description: "Sestavy / Programy - Exempláře - ČR evidence",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 7,
    name: "Rodokmen",
    description: "Sestavy / Programy - Exempláře - Rodokmen",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 8,
    name: "Potomci",
    description: "Sestavy / Programy - Exempláře - Potomci",
    link: "notimplemented",
    type: PrintReportType.Specimen,
  },
  {
    id: 9,
    name: "Historie",
    description: "Sestavy/Programy-Druhy-Historie",
    link: "notimplemented",
    type: PrintReportType.Species,
  },
  {
    id: 10,
    name: "Druh v majetku",
    description: "Sestavy/Programy-Druhy-Druh v majetku",
    link: "species/in-zoo",
    type: PrintReportType.Species,
  },
  {
    id: 11,
    name: "Druh v období",
    description: "Sestavy/Programy-Druhy-Druh v období",
    link: "notimplemented",
    type: PrintReportType.Species,
  },
  {
    id: 12,
    name: "Druh - poznámka",
    description: "Sestavy/Programy-Druhy-Druh - poznámka",
    link: "notimplemented (not used)",
    type: PrintReportType.Species,
  },
  {
    id: 13,
    name: "Hromadný výkon pro druh",
    description: "Sestavy/Programy-Druhy-Hromadný výkon pro druh",
    link: "notimplemented (action - not in list)",
    type: PrintReportType.Species,
  },
  {
    id: 14,
    name: "Pohyb v období s vlivem na stav v zoo",
    description:
      "Sestavy/Programy-Zoologie-Pohyb v období s vlivem na stav v zoo",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 15,
    name: "Pohyb v období bez vlivu na stav v zoo",
    description:
      "Sestavy/Programy-Zoologie-Pohyb v období bez vlivu na stav v zoo",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 16,
    name: "Pohyb v zoo podle data",
    description: "Sestavy/Programy-Zoologie-Pohyb v zoo podle data",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 17,
    name: "Pohyb v zoo podle druhů",
    description: "Sestavy/Programy-Zoologie-Pohyb v zoo podle druhu",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 18,
    name: "Pohyb v zoo podle rajonů",
    description: "Sestavy/Programy-Zoologie-Pohyb v zoo podle rajonu",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 19,
    name: "Pohyb podle partnerů",
    description: "Sestavy/Programy-Zoologie-Pohyb podle partnerů",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 20,
    name: "V majetku",
    description: "Sestavy/Programy-Zoologie-V majetku",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 21,
    name: "V majetku (hromadně)",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně)",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 22,
    name: "V majetku (hromadně) s reg. povinn.",
    description:
      "Sestavy/Programy-Zoologie-V majetku (hromadně) s reg. povinností",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 23,
    name: "V majetku (hromadně) ZCHD ČR",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) ZCHD ČR",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 24,
    name: "V majetku (hromadně) s EU fauna",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) s EU fauna",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 25,
    name: "V majetku (hromadně) bez EUpermit s reg. povinn.",
    description:
      "Sestavy/Programy-Zoologie-V majetku (hromadně) bez Eupermit s reg. povinností",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 26,
    name: "V majetku (hromadně) bez EUpermit",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) bez Eupermit",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 27,
    name: "V majetku (hromadně) ne 've stavu'",
    description: "Sestavy/Programy-Zoologie-V majetku (hromadně) ne 've stavu'",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 28,
    name: "V majetku (hromadně) podle rozhodnutí",
    description:
      "Sestavy/Programy-Zoologie-V majetku (hromadně) podle rozhodnutí",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 29,
    name: "V majetku po rajonech",
    description: "Sestavy/Programy-Zoologie-V majetku po rajonech",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 30,
    name: "V majetku rajonu",
    description: "Sestavy/Programy-Zoologie-V majetku rajonu",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 31,
    name: "V majetku úseku",
    description: "Sestavy/Programy-Zoologie-V majetku úseku",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 32,
    name: "Seznam exemplářů pro ARKS v období",
    description: "Sestavy/Programy-Zoologie-Seznam exemplářů pro ARKS v období",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 33,
    name: "Kompletní seznam - ARKS",
    description: "Sestavy/Programy-Zoologie-Kompletní seznam - ARKS",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 34,
    name: "Seznam registrací - podle čísla registrace",
    description:
      "Sestavy/Programy-Zoologie- Seznam registrací - podle čísla registrace",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 35,
    name: "Seznam registrací - podle data úbytku",
    description:
      "Sestavy/Programy-Zoologie- Seznam registrací - podle data úbytku",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 36,
    name: "Seznam EU-permit - podle čísla ",
    description: "Sestavy/Programy-Zoologie- Seznam EU-permit - podle čísla",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 37,
    name: "ČR evidence - podle data pohybu",
    description: "Sestavy/Programy-Zoologie- ČR evidence - podle data pohybu",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 38,
    name: "ČR rozhodnutí - podle data pohybu",
    description: "Sestavy/Programy-Zoologie- ČR rozhodnutí - podle data pohybu",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 39,
    name: "Narození v období",
    description: "Sestavy/Programy-Zoologie- Narození v období",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 40,
    name: "Statistika narození",
    description: "Sestavy/Programy-Zoologie- Statistika narození",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 41,
    name: "Statistika ke dni",
    description: "Sestavy/Programy-Zoologie- Statistika ke dni",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 42,
    name: "Statistika ke dni s mez. programy",
    description:
      "Sestavy/Programy-Zoologie- Statistika ke dni s mez. programy",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 43,
    name: "Statistika ke dni s mez. programy dle MŽP ČR",
    description:
      "Sestavy/Programy-Zoologie- Statistika ke dni s mez. programy dle MZP ČR",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 44,
    name: "Statistika ke dni podle řádů",
    description: "Sestavy/Programy-Zoologie- Statistika ke dni podle řádu",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 45,
    name: "Přehled druhů 'eu-odchylka'",
    description: "Sestavy/Programy-Zoologie- Přehled druhu EU odchylka",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 46,
    name: "Zvláště chráněné druhy ČR",
    description: "Sestavy/Programy-Zoologie- Zvláště chráněné druhy ČR",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 47,
    name: "EU fauna",
    description: "Sestavy/Programy-Zoologie- EU fauna",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 48,
    name: "Kadáver v období",
    description: "Sestavy/Programy-Zoologie- Kadáver v období",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 49,
    name: "Kadáver v období pro druh",
    description:
      "Sestavy/Programy-Zoologie- Kadáver v období pro druh",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 50,
    name: "Kadáver v období pro místo",
    description:
      "Sestavy/Programy-Zoologie- Kadáver v období pro místo",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 51,
    name: "Přehled záznamů kadáver v období",
    description: "Sestavy/Programy-Zoologie- Přehled záznamů kadáverů v období",
    link: "notimplemented",
    type: PrintReportType.Zoology,
  },
  {
    id: 52,
    name: "Inventura",
    description: "Sestavy/Programy-Ekonomika-Inventura",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 53,
    name: "Inventura (původní verze)",
    description: "Sestavy/Programy-Ekonomika-Inventura (původní verze)",
    link: "notimplemented (not used)",
    type: PrintReportType.Economy,
  },
  {
    id: 54,
    name: "Inventura po rajonech",
    description: "Sestavy/Programy-Ekonomika-Inventura po rajonech",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 55,
    name: "Inventura rajonů",
    description: "Sestavy/Programy-Ekonomika-Inventura rajonu",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 56,
    name: "Inventura úseku",
    description: "Sestavy/Programy - Ekonomika - Inventura úseku",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 57,
    name: "Přehled ekonomiky pohybu",
    description: "Sestavy/Programy - Ekonomika - Přehled ekonomiky pohybu",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 58,
    name: "Rekapitulace ekonomiky pohybu",
    description: "Sestavy/Programy - Ekonomika - Rekapitulace ekonomiky pohybu",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 59,
    name: "Rekapitulace ekonomiky pohybu (původní verze)",
    description:
      "Sestavy/Programy - Ekonomika - Rekapitulace ekonomiky pohybu (původní verze)",
    link: "notimplemented (not used)",
    type: PrintReportType.Economy,
  },
  {
    id: 60,
    name: "Ekonomika pohybu - podle tříd",
    description: "Sestavy/Programy - Ekonomika - Ekonomika pohybu - podle tříd",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 61,
    name: "Přehled pohybu - koupě/prodej",
    description: "Sestavy/Programy - Ekonomika - Přehled pohybu - koupě/prodej",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 62,
    name: "Přehled smluv podle masky čísla smlouvy",
    description:
      "Sestavy/Programy - Ekonomika - Přehled smluv podle masky čísla smlouvy",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 63,
    name: "Přehled smluv za období",
    description: "Sestavy/Programy - Ekonomika - Přehled smluv za období",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 64,
    name: "Deponace",
    description: "Sestavy/Programy-Ekonomika-Deponace",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 65,
    name: "Deponace (původní verze)",
    description: "Sestavy/Programy-Ekonomika-Deponace (původní verze)",
    link: "notimplemented (not used)",
    type: PrintReportType.Economy,
  },
  {
    id: 66,
    name: "Deponace (2016)",
    description: "Sestavy/Programy-Ekonomika-Deponace (2016)",
    link: "notimplemented (not used)",
    type: PrintReportType.Economy,
  },
  {
    id: 67,
    name: "Zabavené ke dni",
    description: "Sestavy/Programy-Ekonomika-Zabavené ke dni",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 68,
    name: "Zabavené ke dni (b)",
    description: "Sestavy/Programy-Ekonomika-Zabavené ke dni (b)",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 69,
    name: "Zabavené exempláře ke dni",
    description: "Sestavy/Programy-Ekonomika-Zabavené exempláře ke dni",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 70,
    name: "Zabavené exempláře ke dni (b)",
    description: "Sestavy/Programy-Ekonomika-Zabavené exempláře ke dni (b)",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 71,
    name: "Zabavené exempláře - všechny",
    description: "Sestavy/Programy-Ekonomika-Zabavené exempláře - všechny",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 72,
    name: "Zabavené exempláře - všechny (b)",
    description: "Sestavy/Programy-Ekonomika-Zabavené exempláře - všechny (b)",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 73,
    name: "Zabavené exempláře - krmné dny",
    description: "Sestavy/Programy-Ekonomika-Zabavené exempláře - krmné dny",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 74,
    name: "Krmné dny druhu",
    description: "Sestavy/Programy - Ekonomika - Krmné dny druhu",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 75,
    name: "Krmné dny pro dotaci",
    description: " Sestavy/Programy - Ekonomika - Krmné dny pro dotaci",
    link: "notimplemented",
    type: PrintReportType.Economy,
  },
  {
    id: 76,
    name: "Extrakt druhů dotačního titulu",
    description: "Sestavy / Programy - Mzpr - Extrakt druhu dotačního titulu",
    link: "notimplemented (not used)",
    type: PrintReportType.Mzpr,
  },
  {
    id: 77,
    name: "Struktura nákladových skupin",
    description: "Sestavy / Programy - Mzpr - Struktura nákladových skupin",
    link: "notimplemented (not used)",
    type: PrintReportType.Mzpr,
  },
  {
    id: 78,
    name: "Pohyb podle partneru",
    description: "Sestavy / Programy - Zoologie - Pohyb podle partnerů",
    link: "zoology/movement-in-zoo-by-partner",
    type: PrintReportType.Zoology,
  },
  {
    id: 79,
    name: "Dotaz k deponacím - CZ",
    description: "Sestavy/Korespondence - Dotaz k deponacím - česká verze",
    link: "notimplemented",
    type: PrintReportType.Correspondence,
  },
  {
    id: 80,
    name: "Dotaz k deponacím - ENG",
    description: "Sestavy/Korespondence - Dotaz k deponacím - anglická verze",
    link: "notimplemented",
    type: PrintReportType.Correspondence,
  },
  {
    id: 81,
    name: "Obálka",
    description: "Obálka pro partnery a zahrady",
     link: "notimplemented",
    type: PrintReportType.Economy,
  }
];
