CREATE TABLE ADRESAR (
    ADRESAR_ID  INTEGER NOT NULL,
    HESLO       VARCHAR(128) NOT NULL COLLATE PXW_CSY,
    NAZEV       VARCHAR(255) COLLATE PXW_CSY,
    STATUT      VARCHAR(128) COLLATE PXW_CSY,
    MESTO       VARCHAR(128) COLLATE PXW_CSY,
    ULICECIS    VARCHAR(128) COLLATE PXW_CSY,
    PSC         VARCHAR(10) COLLATE PXW_CSY,
    STAT        VARCHAR(64) COLLATE PXW_CSY,
    TELEFON     VARCHAR(64) COLLATE PXW_CSY,
    FAX         VARCHAR(20) COLLATE PXW_CSY,
    EMAIL       VARCHAR(64) COLLATE PXW_CSY,
    TYP         VARCHAR(4) COLLATE PXW_CSY,
    PRIJMENI    VARCHAR(128) COLLATE PXW_CSY,
    JMENO       VARCHAR(128) COLLATE PXW_CSY,
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 80
);

CREATE TABLE ADRUH (
    PORADI  INTEGER NOT NULL,
    ADRUH   VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE AUCASTNIK (
    PORADI     INTEGER NOT NULL,
    AUCASTNIK  VARCHAR(32) COLLATE PXW_CSY
);

CREATE TABLE AUKON (
    PORADI  INTEGER NOT NULL,
    AUKON   VARCHAR(32) COLLATE PXW_CSY
);

CREATE TABLE AVYKON (
    PORADI  INTEGER NOT NULL,
    AVYKON  VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE AZNACENI (
    PORADI  INTEGER NOT NULL,
    TYP     VARCHAR(32) NOT NULL COLLATE PXW_CSY
);

CREATE TABLE BARVA (
    PORADI    INTEGER NOT NULL,
    COLOR_EN  VARCHAR(16) NOT NULL,
    COLOR_CZ  VARCHAR(16) COLLATE PXW_CSY,
    COLOR_SK  VARCHAR(16) COLLATE PXW_CSY,
    COLOR_DE  VARCHAR(16) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    RGB       VARCHAR(24),
    NICK      VARCHAR(2)
);

CREATE TABLE BOOL (
    BOOL     VARCHAR(1) NOT NULL COLLATE PXW_CSY,
    TEXT_CZ  VARCHAR(16) COLLATE PXW_CSY,
    CHAR_CZ  VARCHAR(16) COLLATE PXW_CSY,
    TEXT_EN  VARCHAR(5) COLLATE PXW_CSY,
    CHAR_EN  VARCHAR(1) COLLATE PXW_CSY
);

CREATE TABLE CELED (
    CELED_ID   INTEGER NOT NULL,
    RAD_ID     INTEGER NOT NULL,
    NAZEV_CZ   VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(128) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(32) COLLATE PXW_CSY,
    KOD        VARCHAR(3) COLLATE PXW_CSY,
    POZNAMKA   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SYNONYMA   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE CELED_B (
    CELED_ID   INTEGER NOT NULL,
    RAD_ID     INTEGER NOT NULL,
    NAZEV_CZ   VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(128) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(32) COLLATE PXW_CSY,
    KOD        VARCHAR(3) COLLATE PXW_CSY,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE CITES (
    CITES  VARCHAR(4) NOT NULL COLLATE PXW_CSY
);

CREATE TABLE CROCHRANA (
    PORADI     INTEGER NOT NULL,
    CROCHRANA  VARCHAR(3) COLLATE PXW_CSY
);

CREATE TABLE DEPMARK (
    DEPMARK  CHAR(1)
);

CREATE TABLE DOKLADD (
    DOKLADD_ID   INTEGER NOT NULL,
    DRUH_ID      INTEGER NOT NULL,
    DRUHDOKLADU  VARCHAR(16) NOT NULL COLLATE PXW_CSY,
    DATUM        VARCHAR(16) COLLATE PXW_CSY,
    CISLO        VARCHAR(128) NOT NULL COLLATE PXW_CSY,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    PLATNY       VARCHAR(3) NOT NULL COLLATE PXW_CSY,
    GIOS$KDO     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY     VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE DOKLADE (
    DOKLADE_ID   INTEGER NOT NULL,
    EXEMPLAR_ID  INTEGER NOT NULL,
    DRUHDOKLADU  VARCHAR(16) NOT NULL COLLATE PXW_CSY,
    CISLO        VARCHAR(128) NOT NULL COLLATE PXW_CSY,
    DATUM        VARCHAR(16) COLLATE PXW_CSY,
    PARTNER      VARCHAR(32) COLLATE PXW_CSY,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    PLATNY       VARCHAR(3) NOT NULL COLLATE PXW_CSY,
    GIOS$KDO     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY     VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE DRUH (
    DRUH_ID           INTEGER NOT NULL,
    ROD_ID            INTEGER NOT NULL,
    KOD               VARCHAR(6) COLLATE PXW_CSY,
    NAZEV_CZ          VARCHAR(255) COLLATE PXW_CSY,
    NAZEV_LAT         VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_EN          VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_GE          VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_SK          VARCHAR(255) COLLATE PXW_CSY,
    KARTA             VARCHAR(10) COLLATE PXW_CSY,
    RDB               VARCHAR(48) COLLATE PXW_CSY,
    CITES             VARCHAR(4) COLLATE PXW_CSY,
    CROCHRANA         VARCHAR(3) COLLATE PXW_CSY,
    EEP               CHAR(3),
    ESB               CHAR(3),
    ISB               CHAR(3),
    GENOFOND          CHAR(3),
    TYP               VARCHAR(1) NOT NULL COLLATE PXW_CSY,
    STAVZOO           VARCHAR(1) COLLATE PXW_CSY,
    CENA              VARCHAR(16),
    RAJON_ID          INTEGER,
    POZNAMKA          BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SYNONYMA          BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    POPIS             BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    KRMNADAVKA        VARCHAR(1) COLLATE PXW_CSY,
    FOTO              BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    GIOS$KDO          VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY          VARCHAR(24) COLLATE PXW_CSY,
    INYBOOK           VARCHAR(1),
    UCSZKOEF          VARCHAR(6) COLLATE PXW_CSY,
    EU                VARCHAR(2) COLLATE PXW_CSY,
    REGPOVINNOST      CHAR(3),
    SKUPINA           VARCHAR(1) COLLATE PXW_CSY,
    EUFAUNA           CHAR(3),
    EUFAUNACJ         VARCHAR(200) COLLATE PXW_CSY,
    CRVYJIMKACJ       VARCHAR(200) COLLATE PXW_CSY,
    RDB_PREV          VARCHAR(48) COLLATE PXW_CSY,
    PRUMMINUBYTEKINK  VARCHAR(24),
    PRUMMAXUBYTEKINK  VARCHAR(24),
    PRUMDOBAINK       VARCHAR(24),
    SKUPINAID         INTEGER,
    DOKLADS           VARCHAR(256) COLLATE PXW_CSY
);

CREATE TABLE DRUH_B (
    DRUH_ID     INTEGER NOT NULL,
    ROD_ID      INTEGER NOT NULL,
    KOD         VARCHAR(20) COLLATE PXW_CSY,
    NAZEV_CZ    VARCHAR(255) COLLATE PXW_CSY,
    NAZEV_LAT   VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_EN    VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_GE    VARCHAR(128) COLLATE PXW_CSY,
    NAZEV_SK    VARCHAR(255) COLLATE PXW_CSY,
    KARTA       VARCHAR(10) COLLATE PXW_CSY,
    RDB         VARCHAR(48) COLLATE PXW_CSY,
    CITES       VARCHAR(4) COLLATE PXW_CSY,
    CROCHRANA   VARCHAR(3) COLLATE PXW_CSY,
    EEP         CHAR(3),
    ESB         CHAR(3),
    ISB         CHAR(3),
    GENOFOND    CHAR(3),
    TYP         VARCHAR(1) NOT NULL COLLATE PXW_CSY,
    STAVZOO     VARCHAR(1) COLLATE PXW_CSY,
    CENA        VARCHAR(16),
    RAJON_ID    INTEGER,
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    POPIS       BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SYNONYMA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    KRMNADAVKA  VARCHAR(1) COLLATE PXW_CSY,
    FOTO        BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    GIOS$KDO    VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY    VARCHAR(24) COLLATE PXW_CSY,
    INYBOOK     VARCHAR(1),
    UCSZKOEF    VARCHAR(6) COLLATE PXW_CSY,
    EU          VARCHAR(2) COLLATE PXW_CSY,
    SKUPINA     VARCHAR(1) COLLATE PXW_CSY,
    RDB_PREV    VARCHAR(48) COLLATE PXW_CSY,
    SKUPINAID   INTEGER
);

CREATE TABLE DRUH_VK (
    DRUH_ID           INTEGER NOT NULL,
    PRUMMINUBYTEKINK  VARCHAR(24),
    PRUMMAXUBYTEKINK  VARCHAR(24),
    PRUMDOBAINK       VARCHAR(24)
);

CREATE TABLE DRUHDDRUH (
    PORADI  INTEGER NOT NULL,
    DOKLAD  VARCHAR(16) NOT NULL COLLATE PXW_CSY,
    POPIS   VARCHAR(64) COLLATE PXW_CSY
);

CREATE TABLE DRUHDEXEMPLAR (
    PORADI  INTEGER NOT NULL,
    DOKLAD  VARCHAR(16) NOT NULL COLLATE PXW_CSY,
    POPIS   VARCHAR(64) COLLATE PXW_CSY
);

CREATE TABLE EKONOM (
    EKONOM_ID    INTEGER NOT NULL,
    EXEMPLAR_ID  INTEGER NOT NULL,
    UDAJ         VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    DATUM        VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY     VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE EU (
    EU  VARCHAR(2) NOT NULL COLLATE PXW_CSY
);

CREATE TABLE EXEMPLAR (
    EXEMPLAR_ID     INTEGER NOT NULL,
    DRUH_ID         INTEGER NOT NULL,
    PRIRUSTCISLO    INTEGER,
    POHLAVI         VARCHAR(2) COLLATE PXW_CSY,
    TYP             VARCHAR(1) NOT NULL COLLATE PXW_CSY,
    ARKS            VARCHAR(32) COLLATE PXW_CSY,
    PLEMKNIHACISLO  VARCHAR(32) COLLATE PXW_CSY,
    PLEMKNIHAJMENO  VARCHAR(64) COLLATE PXW_CSY,
    JMENO           VARCHAR(255) COLLATE PXW_CSY,
    VRUB            VARCHAR(255) COLLATE PXW_CSY,
    CHIP            VARCHAR(255) COLLATE PXW_CSY,
    KROUZEKCISLO    VARCHAR(255) COLLATE PXW_CSY,
    JINEZNACENI     VARCHAR(255) COLLATE PXW_CSY,
    HYBRID          CHAR(3),
    UMISTENI        VARCHAR(255) COLLATE PXW_CSY,
    VOLNE           CHAR(3),
    NAROZENIDATUM   VARCHAR(32) COLLATE PXW_CSY,
    NAROZENIMISTO   VARCHAR(64) COLLATE PXW_CSY,
    NAROZENIZPUSOB  VARCHAR(64) COLLATE PXW_CSY,
    ODCHOV          VARCHAR(64) COLLATE PXW_CSY,
    OTEC            INTEGER,
    MATKA           INTEGER,
    POZNAMKA        BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    OSTATNI         BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    FOTO            BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    GIOS$KDO        VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY        VARCHAR(32) COLLATE PXW_CSY,
    REGKDY          VARCHAR(16) COLLATE PXW_CSY,
    REGKOMU         VARCHAR(64) COLLATE PXW_CSY,
    REGISTRACE      VARCHAR(128) COLLATE PXW_CSY,
    KADAVERDATUM    VARCHAR(32) COLLATE PXW_CSY,
    KADAVERMISTO    VARCHAR(32) COLLATE PXW_CSY,
    EUPERMIT        VARCHAR(64) COLLATE PXW_CSY,
    CREVIDENCE      VARCHAR(48) COLLATE PXW_CSY,
    OTEC_ARKS       VARCHAR(32) COLLATE PXW_CSY,
    MATKA_ARKS      VARCHAR(32) COLLATE PXW_CSY,
    KROUZEKCISLOS   VARCHAR(255) COLLATE PXW_CSY,
    JINEZNACENIS    VARCHAR(255),
    CHIPS           VARCHAR(255),
    VRUBS           VARCHAR(255),
    DOKLADS         VARCHAR(256) COLLATE PXW_CSY,
    UELN            VARCHAR(48) COLLATE PXW_CSY
);

CREATE TABLE EXEMPLAR_B (
    EXEMPLAR_ID     INTEGER NOT NULL,
    DRUH_ID         INTEGER NOT NULL,
    PRIRUSTCISLO    INTEGER,
    POHLAVI         VARCHAR(2) COLLATE PXW_CSY,
    TYP             VARCHAR(1) NOT NULL COLLATE PXW_CSY,
    ARKS            VARCHAR(12) COLLATE PXW_CSY,
    PLEMKNIHACISLO  VARCHAR(32) COLLATE PXW_CSY,
    PLEMKNIHAJMENO  VARCHAR(64) COLLATE PXW_CSY,
    JMENO           VARCHAR(128) COLLATE PXW_CSY,
    JINEZNACENI     VARCHAR(128) COLLATE PXW_CSY,
    HYBRID          CHAR(3),
    UMISTENI        VARCHAR(255) COLLATE PXW_CSY,
    VOLNE           CHAR(3),
    NAROZENIDATUM   VARCHAR(16) COLLATE PXW_CSY,
    NAROZENIMISTO   VARCHAR(32) COLLATE PXW_CSY,
    NAROZENIZPUSOB  VARCHAR(32) COLLATE PXW_CSY,
    ODCHOV          VARCHAR(10) COLLATE PXW_CSY,
    POZNAMKA        BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    OSTATNI         BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    FOTO            BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    GIOS$KDO        VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY        VARCHAR(32) COLLATE PXW_CSY,
    REGISTRACE      VARCHAR(128) COLLATE PXW_CSY,
    KADAVERDATUM    VARCHAR(16) COLLATE PXW_CSY,
    KADAVERMISTO    VARCHAR(32) COLLATE PXW_CSY,
    EUPERMIT        VARCHAR(48) COLLATE PXW_CSY,
    CREVIDENCE      VARCHAR(48) COLLATE PXW_CSY
);

CREATE TABLE GIOS$ADMINLOG (
    GIOS$KDO          VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$KDY          VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$APPLICATION  VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    GIOS$COMPUTER     VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    GIOS$STAMP        VARCHAR(16) COLLATE PXW_CSY,
    GIOS$ACTION       VARCHAR(24) COLLATE PXW_CSY,
    GIOS$NOTE         BLOB SUB_TYPE 1 SEGMENT SIZE 80
);

CREATE TABLE GIOS$CONFIG (
    GIOS$CONFIGID  INTEGER NOT NULL,
    GIOS$NAME      VARCHAR(16) COLLATE PXW_CSY,
    GIOS$TYPE      VARCHAR(16) COLLATE PXW_CSY,
    GIOS$USER      VARCHAR(32) COLLATE PXW_CSY,
    GIOS$GROUP     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDO       VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY       VARCHAR(24) NOT NULL,
    GIOS$BLOCK     BLOB SUB_TYPE 1 SEGMENT SIZE 80
);

CREATE TABLE GIOS$EMAIL (
    EMAIL_ID     VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GEMAIL_ID    VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    USE          CHAR(3),
    SENDER       VARCHAR(32) COLLATE PXW_CSY,
    SUBJECT      VARCHAR(128) COLLATE PXW_CSY,
    RECIEVERS    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    BODY         BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    ATTACHMENTS  BLOB SUB_TYPE 1 SEGMENT SIZE 80
);

CREATE TABLE GIOS$GEMAIL (
    GEMAIL_ID  VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    NOTE       VARCHAR(16) COLLATE PXW_CSY,
    DATUM      VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    CAS        VARCHAR(16) COLLATE PXW_CSY
);

CREATE TABLE GIOS$KEY (
    GIOS$TABLE    VARCHAR(31) NOT NULL COLLATE PXW_CSY,
    GIOS$WORKKEY  VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$ID       INTEGER NOT NULL
);

CREATE TABLE GIOS$LOG (
    GIOS$KDO      VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$MODE     VARCHAR(1) COLLATE PXW_CSY,
    GIOS$TABLE    VARCHAR(31) COLLATE PXW_CSY,
    GIOS$COLUMNS  VARCHAR(128) COLLATE PXW_CSY,
    GIOS$BEFORE   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$AFTER    BLOB SUB_TYPE 1 SEGMENT SIZE 80
);

CREATE TABLE GIOS$LOGA (
    GIOS$KDO      VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$MODE     VARCHAR(1) COLLATE PXW_CSY,
    GIOS$TABLE    VARCHAR(31) COLLATE PXW_CSY,
    GIOS$COLUMNS  VARCHAR(128) COLLATE PXW_CSY,
    GIOS$BEFORE   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$AFTER    BLOB SUB_TYPE 1 SEGMENT SIZE 80
);

CREATE TABLE GIOS$SYS (
    GIOS$TAG    VARCHAR(16) NOT NULL COLLATE PXW_CSY,
    GIOS$VALUE  VARCHAR(128) COLLATE PXW_CSY,
    GIOS$MODE   VARCHAR(4) COLLATE PXW_CSY
);

CREATE TABLE GIOS$USERS (
    GIOS$USERID    INTEGER NOT NULL,
    GIOS$USER      VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    GIOS$DBUSER    VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    GIOS$PASSWORD  VARCHAR(64) COLLATE PXW_CSY,
    GIOS$GROUPS    VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDO       VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    GIOS$KDY       VARCHAR(24) NOT NULL COLLATE PXW_CSY
);

CREATE TABLE INFOOBCHOD (
    INFOOBCHODID  INTEGER NOT NULL,
    EXEMPLAR_ID   INTEGER NOT NULL,
    DATUM         VARCHAR(10) COLLATE PXW_CSY,
    ZAMLUVENO     VARCHAR(4) COLLATE PXW_CSY,
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 160,
    GIOS$KDO      VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(24)
);

CREATE TABLE KADAVER (
    KADAVER_ID   INTEGER NOT NULL,
    EXEMPLAR_ID  INTEGER NOT NULL,
    DATUM        VARCHAR(16) COLLATE PXW_CSY,
    MISTO        VARCHAR(32) COLLATE PXW_CSY,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    FOTO         BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    GIOS$KDO     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY     VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE KADRESAR (
    ADRESAR_ID  INTEGER NOT NULL,
    HESLO       VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    NAZEV       VARCHAR(120) COLLATE PXW_CSY,
    MESTO       VARCHAR(48) COLLATE PXW_CSY,
    ULICECIS    VARCHAR(32) COLLATE PXW_CSY,
    PSC         VARCHAR(10) COLLATE PXW_CSY,
    STAT        VARCHAR(64) COLLATE PXW_CSY,
    TELEFON     VARCHAR(20) COLLATE PXW_CSY,
    FAX         VARCHAR(20) COLLATE PXW_CSY,
    EMAIL       VARCHAR(32) COLLATE PXW_CSY,
    PRIJMENI    VARCHAR(32) COLLATE PXW_CSY,
    JMENO       VARCHAR(16) COLLATE PXW_CSY,
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO    VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY    VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE KARTADRUHU (
    KARTA_ID  VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    DRUH_ID   INTEGER,
    POT       INTEGER,
    POR       INTEGER,
    PSS       INTEGER,
    SVJ       INTEGER,
    OVJ       INTEGER,
    POHLAVI   VARCHAR(2) COLLATE PXW_CSY,
    U5D       INTEGER,
    U3M       INTEGER,
    DATUM     VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    POZNAMKA  BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO  VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY  VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE KMEN_B (
    KMEN_ID    INTEGER NOT NULL,
    NAZEV_CZ   VARCHAR(16) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(16) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(16) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(24) COLLATE PXW_CSY,
    KOD        VARCHAR(2) COLLATE PXW_CSY,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE KROUZEK (
    ID            INTEGER NOT NULL,
    EXEMPLAR_ID   INTEGER NOT NULL,
    KROUZEKCISLO  VARCHAR(32) COLLATE PXW_CSY,
    BARVA         VARCHAR(16) COLLATE PXW_CSY,
    STRANA        VARCHAR(2) COLLATE PXW_CSY,
    DATUM         VARCHAR(16) COLLATE PXW_CSY,
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO      VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(24) COLLATE PXW_CSY,
    PLATNY        CHAR(1) NOT NULL,
    UMISTENI      VARCHAR(2) COLLATE PXW_CSY,
    TYPZNACENI    VARCHAR(32) COLLATE PXW_CSY
);

CREATE TABLE MZPRSKUPINY (
    SKUPINAID  INTEGER NOT NULL,
    TRIDA_ID   INTEGER NOT NULL,
    KATEGORIE  VARCHAR(64) COLLATE PXW_CSY,
    NICK       VARCHAR(64) COLLATE PXW_CSY,
    POPIS      VARCHAR(256) COLLATE PXW_CSY,
    VZOR       VARCHAR(256) COLLATE PXW_CSY,
    KRMENI     VARCHAR(32) COLLATE PXW_CSY,
    NAKLADY    VARCHAR(32) COLLATE PXW_CSY,
    POZNAMKA   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(32)
);

CREATE TABLE MZPRZOOSET (
    ZOOSETID    INTEGER NOT NULL,
    SKUPINAID   INTEGER NOT NULL,
    ZAHRADA_ID  VARCHAR(3) NOT NULL,
    KRMENI      VARCHAR(10) COLLATE PXW_CSY,
    NAKLADY     VARCHAR(10) COLLATE PXW_CSY,
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO    VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY    VARCHAR(24)
);

CREATE TABLE NARZPUSOB (
    PORADI     INTEGER NOT NULL,
    NARZPUSOB  VARCHAR(16) COLLATE PXW_CSY
);

CREATE TABLE ODCHOV (
    PORADI  INTEGER NOT NULL,
    ODCHOV  VARCHAR(10) COLLATE PXW_CSY
);

CREATE TABLE PLKNIHA (
    PLKNIHA_ID  INTEGER NOT NULL,
    DRUH_ID     INTEGER NOT NULL,
    DATUM       VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO    VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY    VARCHAR(32) COLLATE PXW_CSY,
    SIGNATURA   VARCHAR(10) COLLATE PXW_CSY
);

CREATE TABLE POHLAVI (
    PORADI   INTEGER NOT NULL,
    POHLAVI  VARCHAR(2) COLLATE PXW_CSY
);

CREATE TABLE POHYB (
    ID            INTEGER NOT NULL,
    EXEMPLAR_ID   INTEGER NOT NULL,
    DATUM         VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    POCET         INTEGER NOT NULL,
    POCETR        INTEGER NOT NULL,
    PRIRUSTEK     VARCHAR(128) COLLATE PXW_CSY,
    UBYTEK        VARCHAR(128) COLLATE PXW_CSY,
    MISTO         INTEGER,
    CITES_DOVOZ   VARCHAR(50) COLLATE PXW_CSY,
    CITES_VYVOZ   VARCHAR(50) COLLATE PXW_CSY,
    CENA          VARCHAR(16),
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO      VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(32) COLLATE PXW_CSY,
    SDRPOHLAVI    VARCHAR(16),
    DATUMU        VARCHAR(16) COLLATE PXW_CSY,
    CENAK         VARCHAR(16) COLLATE PXW_CSY,
    DEP           CHAR(1),
    CISLOSMLOUVY  VARCHAR(32) COLLATE PXW_CSY,
    POZNSMLOUVY   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SMLOUVAID     INTEGER
);

CREATE TABLE POHYB_B (
    ID            INTEGER NOT NULL,
    EXEMPLAR_ID   INTEGER NOT NULL,
    DATUM         VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    POCET         INTEGER NOT NULL,
    POCETR        INTEGER NOT NULL,
    PRIRUSTEK     VARCHAR(128) COLLATE PXW_CSY,
    UBYTEK        VARCHAR(128) COLLATE PXW_CSY,
    MISTO         INTEGER,
    CITES_DOVOZ   VARCHAR(50) COLLATE PXW_CSY,
    CITES_VYVOZ   VARCHAR(50) COLLATE PXW_CSY,
    CENA          VARCHAR(16),
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO      VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(32) COLLATE PXW_CSY,
    SDRPOHLAVI    VARCHAR(16),
    DATUMU        VARCHAR(16) COLLATE PXW_CSY,
    CENAK         VARCHAR(16) COLLATE PXW_CSY,
    DEP           CHAR(1),
    CISLOSMLOUVY  VARCHAR(32) COLLATE PXW_CSY,
    POZNSMLOUVY   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SMLOUVAID     INTEGER
);

CREATE TABLE PRIRUSTEK (
    PORADI     INTEGER NOT NULL,
    PRIRUSTEK  VARCHAR(20) COLLATE PXW_CSY,
    DEPZ       CHAR(1),
    DEPD       CHAR(1),
    DEPZDES    VARCHAR(32) COLLATE PXW_CSY,
    DEPDDES    VARCHAR(32) COLLATE PXW_CSY,
    SMLOUVA    CHAR(1)
);

CREATE TABLE RAD (
    RAD_ID     INTEGER NOT NULL,
    TRIDA_ID   INTEGER NOT NULL,
    KOD        VARCHAR(2) COLLATE PXW_CSY,
    NAZEV_CZ   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(24) COLLATE PXW_CSY,
    POZNAMKA   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SYNONYMA   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE RAD_B (
    RAD_ID     INTEGER NOT NULL,
    TRIDA_ID   INTEGER NOT NULL,
    KOD        VARCHAR(2) COLLATE PXW_CSY,
    NAZEV_CZ   VARCHAR(64) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(64) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(21) COLLATE PXW_CSY,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE RAJON (
    RAJON_ID  INTEGER NOT NULL,
    USEK_ID   INTEGER NOT NULL,
    RAJON     VARCHAR(128) NOT NULL COLLATE PXW_CSY,
    KOD       VARCHAR(4) COLLATE PXW_CSY,
    PROVOZ    VARCHAR(128) COLLATE PXW_CSY
);

CREATE TABLE RDB (
    RDB  VARCHAR(2) NOT NULL COLLATE PXW_CSY
);

CREATE TABLE REDPOHYB (
    EXEMPLAR_ID      INTEGER NOT NULL,
    PRIRUSTEK_DATUM  VARCHAR(10) COLLATE PXW_CSY,
    PRIRUSTEK        VARCHAR(32) COLLATE PXW_CSY,
    PRIRUSTEK_MISTO  VARCHAR(128) COLLATE PXW_CSY,
    UBYTEK_DATUM     VARCHAR(10) COLLATE PXW_CSY,
    UBYTEK           VARCHAR(32) COLLATE PXW_CSY,
    UBYTEK_MISTO     VARCHAR(128) COLLATE PXW_CSY,
    CENA             VARCHAR(16),
    POCET            INTEGER,
    UMISTENI_DATUM   VARCHAR(10) COLLATE PXW_CSY,
    RAJON_ID         INTEGER
);

CREATE TABLE REDPOHYB_B (
    EXEMPLAR_ID      INTEGER NOT NULL,
    PRIRUSTEK_DATUM  VARCHAR(10) COLLATE PXW_CSY,
    PRIRUSTEK        VARCHAR(32) COLLATE PXW_CSY,
    PRIRUSTEK_MISTO  VARCHAR(128) COLLATE PXW_CSY,
    UBYTEK_DATUM     VARCHAR(10) COLLATE PXW_CSY,
    UBYTEK           VARCHAR(32) COLLATE PXW_CSY,
    UBYTEK_MISTO     VARCHAR(128) COLLATE PXW_CSY,
    CENA             VARCHAR(16),
    POCET            INTEGER,
    UMISTENI_DATUM   VARCHAR(10) COLLATE PXW_CSY,
    RAJON_ID         INTEGER
);

CREATE TABLE REGPUVOD (
    PORADI  INTEGER NOT NULL,
    KOD     VARCHAR(1) COLLATE PXW_CSY,
    POPIS   VARCHAR(128) COLLATE PXW_CSY
);

CREATE TABLE ROCENKA (
    ROCENKA_ID  VARCHAR(24) NOT NULL COLLATE PXW_CSY,
    ZAHRADA     VARCHAR(3) COLLATE PXW_CSY,
    ROK         VARCHAR(4) COLLATE PXW_CSY,
    TRIDAZKR    VARCHAR(3) COLLATE PXW_CSY,
    DRUHW       VARCHAR(12) COLLATE PXW_CSY,
    DRUH_ID     INTEGER,
    PST_M       INTEGER,
    PST_F       INTEGER,
    PST_U       INTEGER,
    PRI_M       INTEGER,
    PRI_F       INTEGER,
    PRI_U       INTEGER,
    ODC_M       INTEGER,
    ODC_F       INTEGER,
    ODC_U       INTEGER,
    UHY_M       INTEGER,
    UHY_F       INTEGER,
    UHY_U       INTEGER,
    UBY_M       INTEGER,
    UBY_F       INTEGER,
    UBY_U       INTEGER,
    POT         INTEGER,
    POR         INTEGER,
    MNM_M       INTEGER,
    MNM_F       INTEGER,
    MNM_U       INTEGER,
    ZNM_M       INTEGER,
    ZNM_F       INTEGER,
    ZNM_U       INTEGER,
    PSS         INTEGER,
    SVJ         INTEGER,
    OVJ         INTEGER,
    U5D_M       INTEGER,
    U5D_F       INTEGER,
    U5D_U       INTEGER,
    U3M_M       INTEGER,
    U3M_F       INTEGER,
    U3M_U       INTEGER,
    UKR_M       INTEGER,
    UKR_F       INTEGER,
    UKR_U       INTEGER,
    ODM_M       INTEGER,
    ODM_F       INTEGER,
    ODM_U       INTEGER,
    DEP_M       INTEGER,
    DEP_F       INTEGER,
    DEP_U       INTEGER,
    KST_M       INTEGER,
    KST_F       INTEGER,
    MOVE        VARCHAR(24) COLLATE PXW_CSY,
    TEXT        VARCHAR(12) COLLATE PXW_CSY,
    NAZEV       BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    POZN        BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    KST_U       INTEGER,
    CHM_M       INTEGER,
    CHM_F       INTEGER,
    CHM_U       INTEGER,
    NAZEV_CZ    VARCHAR(255) COLLATE PXW_CSY,
    NAZEV_LAT   VARCHAR(255) COLLATE PXW_CSY,
    NAZEV_SK    VARCHAR(255) COLLATE PXW_CSY,
    REDAKCE     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO    VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY    VARCHAR(32) COLLATE PXW_CSY,
    ZAB         INTEGER,
    NAZEV_EN    VARCHAR(255)
);

CREATE TABLE ROD (
    ROD_ID     INTEGER NOT NULL,
    CELED_ID   INTEGER NOT NULL,
    NAZEV_CZ   VARCHAR(64) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(64) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(32) COLLATE PXW_CSY,
    KOD        VARCHAR(3) COLLATE PXW_CSY,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE ROD_B (
    ROD_ID     INTEGER NOT NULL,
    CELED_ID   INTEGER NOT NULL,
    NAZEV_CZ   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(24) COLLATE PXW_CSY,
    KOD        VARCHAR(3) COLLATE PXW_CSY,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE SMLOUVA (
    SMLOUVAID     INTEGER NOT NULL,
    CISLO         VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    DATUM         VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    POHYB         VARCHAR(21) COLLATE PXW_CSY,
    DRUH          VARCHAR(24),
    PARTNER       INTEGER,
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    POZN_PRAHA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    POZN_PARTNER  BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO      VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(24),
    ROK           VARCHAR(4)
);

CREATE TABLE SMLOUVAROKY (
    ROK  VARCHAR(10) COLLATE PXW_CSY
);

CREATE TABLE STAV (
    STAV   VARCHAR(2) NOT NULL COLLATE PXW_CSY,
    POPIS  VARCHAR(16) COLLATE PXW_CSY
);

CREATE TABLE STRANA (
    STRANA   VARCHAR(1) NOT NULL,
    TEXT_CZ  VARCHAR(24) COLLATE PXW_CSY,
    CHAR_CZ  VARCHAR(1),
    TEXT_EN  VARCHAR(24),
    CHAR_EN  VARCHAR(1)
);

CREATE TABLE TRIDA (
    TRIDA_ID    INTEGER NOT NULL,
    KOD         VARCHAR(2) COLLATE PXW_CSY,
    NAZEV_CZ    VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_LAT   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_EN    VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_SK    VARCHAR(32) COLLATE PXW_CSY,
    KRYPTOGRAM  VARCHAR(5) COLLATE PXW_CSY,
    GIOS$KDO    VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY    VARCHAR(24) COLLATE PXW_CSY,
    IMAGE       VARCHAR(32) COLLATE PXW_CSY,
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    SYNONYMA    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    STAVZOO     VARCHAR(1),
    INYBOOK     VARCHAR(1),
    TRIDAZKR    VARCHAR(3) COLLATE PXW_CSY
);

CREATE TABLE TRIDA_B (
    TRIDA_ID   INTEGER NOT NULL,
    KMEN_ID    INTEGER NOT NULL,
    NAZEV_CZ   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_LAT  VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_EN   VARCHAR(32) COLLATE PXW_CSY,
    NAZEV_SK   VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDO   VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(24) COLLATE PXW_CSY,
    KOD        VARCHAR(2) COLLATE PXW_CSY,
    STAVZOO    VARCHAR(1),
    INYBOOK    VARCHAR(1)
);

CREATE TABLE UBYTEK (
    PORADI   INTEGER NOT NULL,
    UBYTEK   VARCHAR(255) COLLATE PXW_CSY,
    DEPZ     CHAR(1),
    DEPD     CHAR(1),
    DEPZDES  VARCHAR(32) COLLATE PXW_CSY,
    DEPDDES  VARCHAR(32) COLLATE PXW_CSY,
    SMLOUVA  CHAR(1)
);

CREATE TABLE UKONSMLOUVY (
    UKONID     INTEGER NOT NULL,
    SMLOUVAID  INTEGER NOT NULL,
    DATUM      VARCHAR(10) COLLATE PXW_CSY,
    UKON       VARCHAR(32) COLLATE PXW_CSY,
    UCASTNIK   VARCHAR(32) COLLATE PXW_CSY,
    POZNAMKA   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO   VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY   VARCHAR(24)
);

CREATE TABLE UMISTENI (
    UMISTENI_ID   INTEGER NOT NULL,
    EXEMPLAR_ID   INTEGER,
    BEXEMPLAR_ID  INTEGER,
    RAJON_ID      INTEGER NOT NULL,
    DATUM         VARCHAR(16) NOT NULL COLLATE PXW_CSY,
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO      VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE USEK (
    USEK_ID  INTEGER NOT NULL,
    USEK     VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    KOD      VARCHAR(3) COLLATE PXW_CSY
);

CREATE TABLE VKARTA (
    VKARTAID      VARCHAR(24) NOT NULL,
    DRUH_ID       INTEGER NOT NULL,
    OZNACENI      VARCHAR(4),
    OTEC          INTEGER,
    MATKA         INTEGER,
    SNESENID      VARCHAR(10),
    SNESENIC      VARCHAR(5),
    ROZMERMIN     VARCHAR(16),
    ROZMERMAX     VARCHAR(16),
    NAKLUBANID    VARCHAR(10),
    NAKLUBANIC    VARCHAR(5),
    VYLIHNUTID    VARCHAR(10),
    VYLIHNUTIC    VARCHAR(5),
    ZAKLVAHA      VARCHAR(24),
    ZAKLVAHAG     CHAR(1),
    VAHAUBYTEK    VARCHAR(24),
    DELKAINK      VARCHAR(24),
    AKTUALD       VARCHAR(10),
    AKTUALC       VARCHAR(5),
    AKTUALL       VARCHAR(2),
    AKTUALVAHA    VARCHAR(24),
    AKTUALUBYTEK  VARCHAR(24),
    PLAND         VARCHAR(10),
    PLANL         VARCHAR(2),
    GIOS$KDO      CHAR(8),
    GIOS$KDY      CHAR(24),
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 16
);

CREATE TABLE VKARTAA (
    VKARTAID    VARCHAR(24) NOT NULL,
    DRUH_ID     INTEGER NOT NULL,
    OZNACENI    VARCHAR(4),
    OTEC        INTEGER,
    MATKA       INTEGER,
    SNESENID    VARCHAR(10),
    SNESENIC    VARCHAR(5),
    ROZMERMIN   VARCHAR(16),
    ROZMERMAX   VARCHAR(16),
    NAKLUBANID  VARCHAR(10),
    NAKLUBANIC  VARCHAR(5),
    VYLIHNUTID  VARCHAR(10),
    VYLIHNUTIC  VARCHAR(5),
    ZAKLVAHA    VARCHAR(24),
    ZAKLVAHAG   CHAR(1),
    VAHAUBYTEK  VARCHAR(24),
    DELKAINK    VARCHAR(24),
    VAHA        VARCHAR(24),
    UBYTEK      VARCHAR(24),
    GIOS$KDO    CHAR(8),
    GIOS$KDY    CHAR(24),
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 16
);

CREATE TABLE VKLIHEN (
    VKLIHENID  VARCHAR(2) NOT NULL,
    POPIS      VARCHAR(10),
    GIOS$KDO   CHAR(8),
    GIOS$KDY   CHAR(24),
    POZNAMKA   BLOB SUB_TYPE 1 SEGMENT SIZE 16
);

CREATE TABLE VKMERENI (
    ID        VARCHAR(24) NOT NULL,
    VKARTAID  VARCHAR(24) NOT NULL,
    DATUM     VARCHAR(10),
    CAS       VARCHAR(5),
    ROZMERA   VARCHAR(5),
    ROZMERB   VARCHAR(5),
    VAHA      VARCHAR(24),
    VAHAG     CHAR(1),
    UBYTEK    VARCHAR(24),
    GIOS$KDO  CHAR(8),
    GIOS$KDY  CHAR(24),
    POZNAMKA  BLOB SUB_TYPE 1 SEGMENT SIZE 16
);

CREATE TABLE VKNASAZENI (
    ID         VARCHAR(24) NOT NULL,
    VKARTAID   VARCHAR(24) NOT NULL,
    VKLIHENID  VARCHAR(2),
    DATUM      VARCHAR(10),
    CAS        VARCHAR(5),
    VKUDALOST  VARCHAR(32),
    GIOS$KDO   CHAR(8),
    GIOS$KDY   CHAR(24),
    POZNAMKA   BLOB SUB_TYPE 1 SEGMENT SIZE 16
);

CREATE TABLE VKOTACENI (
    VKOTACENIID  VARCHAR(24) NOT NULL,
    VKLIHENID    CHAR(2) NOT NULL,
    PLATNOST     VARCHAR(10),
    CAS01        VARCHAR(5),
    CAS02        VARCHAR(5),
    CAS03        VARCHAR(5),
    CAS04        VARCHAR(5),
    CAS05        VARCHAR(5),
    CAS06        VARCHAR(5),
    CAS07        VARCHAR(5),
    CAS08        VARCHAR(5),
    CAS09        VARCHAR(5),
    CAS10        VARCHAR(5),
    CAS11        VARCHAR(5),
    CAS12        VARCHAR(5),
    CAS13        VARCHAR(5),
    CAS14        VARCHAR(5),
    CAS15        VARCHAR(5),
    CAS16        VARCHAR(5),
    GIOS$KDO     CHAR(8),
    GIOS$KDY     CHAR(24),
    FREKVENCE    INTEGER,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 16
);

CREATE TABLE VKTEPLOTAVLHKOST (
    VKTEPLOTAVLHKOSTID  VARCHAR(24) NOT NULL,
    VKLIHENID           VARCHAR(2) NOT NULL,
    DATUM               VARCHAR(10),
    CAS                 VARCHAR(5),
    TEPLOTA             VARCHAR(5),
    VLHKOST             VARCHAR(5),
    GIOS$KDO            CHAR(8),
    GIOS$KDY            CHAR(24),
    POZNAMKA            BLOB SUB_TYPE 1 SEGMENT SIZE 16
);

CREATE TABLE VKUDALOST (
    VKUDALOST  VARCHAR(24) COLLATE PXW_CSY,
    PORADI     INTEGER NOT NULL
);

CREATE TABLE VKWOTACENICAS (
    CAS  VARCHAR(5)
);

CREATE TABLE VYKONY (
    ID           INTEGER NOT NULL,
    EXEMPLAR_ID  INTEGER NOT NULL,
    DATUM        VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    VYKON        VARCHAR(22) COLLATE PXW_CSY,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY     VARCHAR(24) COLLATE PXW_CSY,
    PARTNER      INTEGER
);

CREATE TABLE VYKONY_B (
    ID           INTEGER NOT NULL,
    EXEMPLAR_ID  INTEGER NOT NULL,
    DATUM        VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    VYKON        VARCHAR(22) COLLATE PXW_CSY,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY     VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE VYSKA (
    PORADI   INTEGER NOT NULL,
    TEXT_CZ  VARCHAR(24) COLLATE PXW_CSY,
    CHAR_CZ  VARCHAR(2),
    TEXT_EN  VARCHAR(24),
    CHAR_EN  VARCHAR(2) NOT NULL
);

CREATE TABLE WGIOS$STATISTIKA_EEP (
    TRIDA_ID   INTEGER,
    DRUH_ID    INTEGER,
    MALE       INTEGER,
    FEMALE     INTEGER,
    ODD        INTEGER,
    EEP        INTEGER,
    ESB        INTEGER,
    ISB        INTEGER,
    CROCHRANA  INTEGER,
    RDB        INTEGER,
    CITES      INTEGER,
    EU         INTEGER
);

CREATE TABLE ZAHRADY (
    ZAHRADA_ID  VARCHAR(3) NOT NULL COLLATE PXW_CSY,
    HESLO       VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    NAZEV       VARCHAR(120) COLLATE PXW_CSY,
    MESTO       VARCHAR(48) COLLATE PXW_CSY,
    ULICECIS    VARCHAR(32) COLLATE PXW_CSY,
    PSC         VARCHAR(10) COLLATE PXW_CSY,
    STAT        VARCHAR(64) COLLATE PXW_CSY,
    TELEFON     VARCHAR(20) COLLATE PXW_CSY,
    FAX         VARCHAR(20) COLLATE PXW_CSY,
    EMAIL       VARCHAR(32) COLLATE PXW_CSY,
    WWW         VARCHAR(64) COLLATE PXW_CSY,
    PRIJMENI    VARCHAR(32) COLLATE PXW_CSY,
    JMENO       VARCHAR(16) COLLATE PXW_CSY,
    POZNAMKA    BLOB SUB_TYPE 1 SEGMENT SIZE 80
);

CREATE TABLE ZAZNAMY (
    ID           INTEGER NOT NULL,
    EXEMPLAR_ID  INTEGER NOT NULL,
    DATUM        VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    VYKON        VARCHAR(22) COLLATE PXW_CSY,
    POZNAMKA     BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO     VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY     VARCHAR(24) COLLATE PXW_CSY,
    PARTNER      INTEGER
);

CREATE TABLE ZAZNAMY_D (
    ID        INTEGER NOT NULL,
    DRUH_ID   INTEGER NOT NULL,
    DATUM     VARCHAR(10) NOT NULL COLLATE PXW_CSY,
    VYKON     VARCHAR(22) COLLATE PXW_CSY,
    POZNAMKA  BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO  VARCHAR(24) COLLATE PXW_CSY,
    GIOS$KDY  VARCHAR(24) COLLATE PXW_CSY
);

CREATE TABLE ZNACENI (
    ID            INTEGER NOT NULL,
    EXEMPLAR_ID   INTEGER NOT NULL,
    TYPZNACENI    VARCHAR(32) NOT NULL COLLATE PXW_CSY,
    KROUZEKCISLO  VARCHAR(32) COLLATE PXW_CSY,
    BARVA         VARCHAR(16) COLLATE PXW_CSY,
    STRANA        VARCHAR(2) COLLATE PXW_CSY,
    UMISTENI      VARCHAR(2) COLLATE PXW_CSY,
    PLATNY        VARCHAR(1) NOT NULL COLLATE PXW_CSY,
    DATUM         VARCHAR(16) COLLATE PXW_CSY,
    POZNAMKA      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GIOS$KDO      VARCHAR(32) COLLATE PXW_CSY,
    GIOS$KDY      VARCHAR(32) COLLATE PXW_CSY
);

